USE LGLS_MCS_IO;
GO

IF NOT EXISTS (SELECT 1 FROM DEST_POS_DEF WHERE MC_NO = '129')
BEGIN
    INSERT INTO DEST_POS_DEF (TRACK_NO, MC_NO, GROUP_NO, REMARKS)
    VALUES ('1029', '129', 'OUT', 'IMS102 C/V#14 피킹출고 TR#29');
    PRINT 'DEST_POS_DEF : 129 (피킹 출고대) 추가';
END
ELSE
    PRINT 'DEST_POS_DEF : 129 이미 있음 - 건너뜀';
GO

-- 확인
SELECT TRACK_NO, MC_NO, GROUP_NO, REMARKS FROM DEST_POS_DEF ORDER BY GROUP_NO, MC_NO;
GO
