[COMMON]
ThreadExitTimeout=5000
SocketRecvTimeout=3000
SocketResendLimit=5
DebugerAssert=1
DebugerTrace=0
LogTrace=0
TabCount=1
StnEqulTr=1
#PlcCnt=1
PlcCnt=5

[LAYOUT]
FontSize=14
L=0
B=0
R=120
T=60

[LENGTH]
StationID=3
ControlID=8
Location=7
Barcode=31

[LOG]
Job=1
Event=1
Error=1
Alarm=1
Debug=1
Beep=0

[HOST]
IP=127.0.0.1
Port=5000
Connect=1
Retry=1
WriteLog=0
ServerPort=8000

[MONITOR]
ServerPort=9001
WriteLog=0

[COLOR]
AutoSto=00ff00
AutoRet=ff0000
AutoMove=ffff00
AutoRtR=ff00ff
AutoWtW=ff0080
SemiSto=008000
SemiRet=800000
SemiMove=808000
SemiRtR=800080
SemiWtW=800040
StoST=ff00ff
RetST=ff8000
ArvST=80ff00
Depart=4080ff
Arrive=808000
Disconnect=ffffff
Suspend=8000ff
Manual=00ffff
Error=0000ff
Alarm=0080ff

[PATH]
Ecs=D:\CompanyProject\아산SFA개발\PLC_SIMULATOR\Source\EcsSv
Job=D:\CompanyProject\아산SFA개발\PLC_SIMULATOR\Source\EcsSv\Job
Log=D:\CompanyProject\아산SFA개발\PLC_SIMULATOR\Source\EcsSv\Log
Stc=D:\CompanyProject\아산SFA개발\PLC_SIMULATOR\Source\EcsSv\Stc
Temp=D:\CompanyProject\아산SFA개발\PLC_SIMULATOR\Source\EcsSv\Temp
PlayBack=D:\Project\SK 이노베이션\2015\30. SOURCE\ECS\Source\EcsSv\PlayBack


[CV_E01]
IP=127.0.0.1
StTrNum=21001

Connect=1
Retry=1
WriteLog=0
RecvTimeout=3000
Port1=9101
Port2=9102
Port3=9103
Port4=9104
Port5=9105
Port6=9106
Port7=9107
Port8=9108
Port9=9109
Port10=9110
Port11=9111
Port12=9112
Port13=9113
Port14=9114
Port15=9115
Port16=9116
Port17=9117
Port18=9118
[CV_E02]
IP=127.0.0.1
Connect=1
Retry=1
WriteLog=0
RecvTimeout=3000
Port1=9201
Port2=9202
Port3=9203
Port4=9204
Port5=9205
Port6=9206
Port7=9207
Port8=9208
Port9=9209
Port10=9210
Port11=9211
Port12=9212
Port13=9213
Port14=9214
Port15=9215
Port16=9216
Port17=9217
Port18=9218
