//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HECS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HECS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap AccessLog {
            get {
                object obj = ResourceManager.GetObject("AccessLog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Alarm {
            get {
                object obj = ResourceManager.GetObject("Alarm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AlarmCount {
            get {
                object obj = ResourceManager.GetObject("AlarmCount", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AlarmCount2 {
            get {
                object obj = ResourceManager.GetObject("AlarmCount2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ALLTransferRate {
            get {
                object obj = ResourceManager.GetObject("ALLTransferRate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Aqua___Play {
            get {
                object obj = ResourceManager.GetObject("Aqua - Play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ArmAxis {
            get {
                object obj = ResourceManager.GetObject("ArmAxis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ATJ_FRONT {
            get {
                object obj = ResourceManager.GetObject("ATJ_FRONT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ATJ_FRONT2 {
            get {
                object obj = ResourceManager.GetObject("ATJ_FRONT2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ATJ_SIDE {
            get {
                object obj = ResourceManager.GetObject("ATJ_SIDE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ATJ_TOP {
            get {
                object obj = ResourceManager.GetObject("ATJ_TOP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap auto {
            get {
                object obj = ResourceManager.GetObject("auto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AVACO_FRONT {
            get {
                object obj = ResourceManager.GetObject("AVACO_FRONT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AVACO_FRONT_SIDE {
            get {
                object obj = ResourceManager.GetObject("AVACO_FRONT_SIDE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AVACO_SIDE {
            get {
                object obj = ResourceManager.GetObject("AVACO_SIDE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AVACO_TOP {
            get {
                object obj = ResourceManager.GetObject("AVACO_TOP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet50005300 {
            get {
                object obj = ResourceManager.GetObject("bullet50005300", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet50006800 {
            get {
                object obj = ResourceManager.GetObject("bullet50006800", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet50010400 {
            get {
                object obj = ResourceManager.GetObject("bullet50010400", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet50016400 {
            get {
                object obj = ResourceManager.GetObject("bullet50016400", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet50043300 {
            get {
                object obj = ResourceManager.GetObject("bullet50043300", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet50043600 {
            get {
                object obj = ResourceManager.GetObject("bullet50043600", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet500436001 {
            get {
                object obj = ResourceManager.GetObject("bullet500436001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet50043900 {
            get {
                object obj = ResourceManager.GetObject("bullet50043900", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet50044200 {
            get {
                object obj = ResourceManager.GetObject("bullet50044200", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet50044500 {
            get {
                object obj = ResourceManager.GetObject("bullet50044500", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet50044800 {
            get {
                object obj = ResourceManager.GetObject("bullet50044800", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet50045100 {
            get {
                object obj = ResourceManager.GetObject("bullet50045100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet50045400 {
            get {
                object obj = ResourceManager.GetObject("bullet50045400", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet50045700 {
            get {
                object obj = ResourceManager.GetObject("bullet50045700", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet50046000 {
            get {
                object obj = ResourceManager.GetObject("bullet50046000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet50046300 {
            get {
                object obj = ResourceManager.GetObject("bullet50046300", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet50046600 {
            get {
                object obj = ResourceManager.GetObject("bullet50046600", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet50046900 {
            get {
                object obj = ResourceManager.GetObject("bullet50046900", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet50053200 {
            get {
                object obj = ResourceManager.GetObject("bullet50053200", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet50053500 {
            get {
                object obj = ResourceManager.GetObject("bullet50053500", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet50053800 {
            get {
                object obj = ResourceManager.GetObject("bullet50053800", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet50055000 {
            get {
                object obj = ResourceManager.GetObject("bullet50055000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet50055300 {
            get {
                object obj = ResourceManager.GetObject("bullet50055300", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet50055600 {
            get {
                object obj = ResourceManager.GetObject("bullet50055600", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet500556001 {
            get {
                object obj = ResourceManager.GetObject("bullet500556001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet50055900 {
            get {
                object obj = ResourceManager.GetObject("bullet50055900", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet50090600 {
            get {
                object obj = ResourceManager.GetObject("bullet50090600", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet50093600 {
            get {
                object obj = ResourceManager.GetObject("bullet50093600", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet50093900 {
            get {
                object obj = ResourceManager.GetObject("bullet50093900", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet50094800 {
            get {
                object obj = ResourceManager.GetObject("bullet50094800", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet50095700 {
            get {
                object obj = ResourceManager.GetObject("bullet50095700", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet50096300 {
            get {
                object obj = ResourceManager.GetObject("bullet50096300", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet50096600 {
            get {
                object obj = ResourceManager.GetObject("bullet50096600", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet50096900 {
            get {
                object obj = ResourceManager.GetObject("bullet50096900", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet50097800 {
            get {
                object obj = ResourceManager.GetObject("bullet50097800", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet50110100 {
            get {
                object obj = ResourceManager.GetObject("bullet50110100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet50202500 {
            get {
                object obj = ResourceManager.GetObject("bullet50202500", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet50202700 {
            get {
                object obj = ResourceManager.GetObject("bullet50202700", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet50250600 {
            get {
                object obj = ResourceManager.GetObject("bullet50250600", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet50261700 {
            get {
                object obj = ResourceManager.GetObject("bullet50261700", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet50262600 {
            get {
                object obj = ResourceManager.GetObject("bullet50262600", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet50401100 {
            get {
                object obj = ResourceManager.GetObject("bullet50401100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53300600 {
            get {
                object obj = ResourceManager.GetObject("bullet53300600", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53301200 {
            get {
                object obj = ResourceManager.GetObject("bullet53301200", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53301400 {
            get {
                object obj = ResourceManager.GetObject("bullet53301400", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53301600 {
            get {
                object obj = ResourceManager.GetObject("bullet53301600", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53303000 {
            get {
                object obj = ResourceManager.GetObject("bullet53303000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53303200 {
            get {
                object obj = ResourceManager.GetObject("bullet53303200", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53307700 {
            get {
                object obj = ResourceManager.GetObject("bullet53307700", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53308100 {
            get {
                object obj = ResourceManager.GetObject("bullet53308100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53308200 {
            get {
                object obj = ResourceManager.GetObject("bullet53308200", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53308600 {
            get {
                object obj = ResourceManager.GetObject("bullet53308600", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53309300 {
            get {
                object obj = ResourceManager.GetObject("bullet53309300", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53309400 {
            get {
                object obj = ResourceManager.GetObject("bullet53309400", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53310000 {
            get {
                object obj = ResourceManager.GetObject("bullet53310000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53312300 {
            get {
                object obj = ResourceManager.GetObject("bullet53312300", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53318400 {
            get {
                object obj = ResourceManager.GetObject("bullet53318400", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53324100 {
            get {
                object obj = ResourceManager.GetObject("bullet53324100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53325100 {
            get {
                object obj = ResourceManager.GetObject("bullet53325100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53326100 {
            get {
                object obj = ResourceManager.GetObject("bullet53326100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53326500 {
            get {
                object obj = ResourceManager.GetObject("bullet53326500", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53348000 {
            get {
                object obj = ResourceManager.GetObject("bullet53348000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53355500 {
            get {
                object obj = ResourceManager.GetObject("bullet53355500", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53381000 {
            get {
                object obj = ResourceManager.GetObject("bullet53381000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53392500 {
            get {
                object obj = ResourceManager.GetObject("bullet53392500", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53418400 {
            get {
                object obj = ResourceManager.GetObject("bullet53418400", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53433100 {
            get {
                object obj = ResourceManager.GetObject("bullet53433100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53460200 {
            get {
                object obj = ResourceManager.GetObject("bullet53460200", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53461600 {
            get {
                object obj = ResourceManager.GetObject("bullet53461600", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53461700 {
            get {
                object obj = ResourceManager.GetObject("bullet53461700", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53461800 {
            get {
                object obj = ResourceManager.GetObject("bullet53461800", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53462000 {
            get {
                object obj = ResourceManager.GetObject("bullet53462000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53462100 {
            get {
                object obj = ResourceManager.GetObject("bullet53462100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53462200 {
            get {
                object obj = ResourceManager.GetObject("bullet53462200", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53462300 {
            get {
                object obj = ResourceManager.GetObject("bullet53462300", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53463600 {
            get {
                object obj = ResourceManager.GetObject("bullet53463600", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53463700 {
            get {
                object obj = ResourceManager.GetObject("bullet53463700", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53464500 {
            get {
                object obj = ResourceManager.GetObject("bullet53464500", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53464700 {
            get {
                object obj = ResourceManager.GetObject("bullet53464700", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53464900 {
            get {
                object obj = ResourceManager.GetObject("bullet53464900", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53465100 {
            get {
                object obj = ResourceManager.GetObject("bullet53465100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53465300 {
            get {
                object obj = ResourceManager.GetObject("bullet53465300", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53471200 {
            get {
                object obj = ResourceManager.GetObject("bullet53471200", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53473600 {
            get {
                object obj = ResourceManager.GetObject("bullet53473600", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53476600 {
            get {
                object obj = ResourceManager.GetObject("bullet53476600", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53478600 {
            get {
                object obj = ResourceManager.GetObject("bullet53478600", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53478800 {
            get {
                object obj = ResourceManager.GetObject("bullet53478800", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53479000 {
            get {
                object obj = ResourceManager.GetObject("bullet53479000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53479200 {
            get {
                object obj = ResourceManager.GetObject("bullet53479200", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53479400 {
            get {
                object obj = ResourceManager.GetObject("bullet53479400", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53479600 {
            get {
                object obj = ResourceManager.GetObject("bullet53479600", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53480000 {
            get {
                object obj = ResourceManager.GetObject("bullet53480000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53483300 {
            get {
                object obj = ResourceManager.GetObject("bullet53483300", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53483900 {
            get {
                object obj = ResourceManager.GetObject("bullet53483900", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53484100 {
            get {
                object obj = ResourceManager.GetObject("bullet53484100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53484300 {
            get {
                object obj = ResourceManager.GetObject("bullet53484300", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53484500 {
            get {
                object obj = ResourceManager.GetObject("bullet53484500", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53485500 {
            get {
                object obj = ResourceManager.GetObject("bullet53485500", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53485700 {
            get {
                object obj = ResourceManager.GetObject("bullet53485700", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53487500 {
            get {
                object obj = ResourceManager.GetObject("bullet53487500", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53487700 {
            get {
                object obj = ResourceManager.GetObject("bullet53487700", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53501300 {
            get {
                object obj = ResourceManager.GetObject("bullet53501300", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53501700 {
            get {
                object obj = ResourceManager.GetObject("bullet53501700", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53501900 {
            get {
                object obj = ResourceManager.GetObject("bullet53501900", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53503100 {
            get {
                object obj = ResourceManager.GetObject("bullet53503100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53505300 {
            get {
                object obj = ResourceManager.GetObject("bullet53505300", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53506900 {
            get {
                object obj = ResourceManager.GetObject("bullet53506900", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53507100 {
            get {
                object obj = ResourceManager.GetObject("bullet53507100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53507500 {
            get {
                object obj = ResourceManager.GetObject("bullet53507500", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53510100 {
            get {
                object obj = ResourceManager.GetObject("bullet53510100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53512500 {
            get {
                object obj = ResourceManager.GetObject("bullet53512500", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53512700 {
            get {
                object obj = ResourceManager.GetObject("bullet53512700", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53512900 {
            get {
                object obj = ResourceManager.GetObject("bullet53512900", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53513500 {
            get {
                object obj = ResourceManager.GetObject("bullet53513500", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53513700 {
            get {
                object obj = ResourceManager.GetObject("bullet53513700", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53513900 {
            get {
                object obj = ResourceManager.GetObject("bullet53513900", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53514100 {
            get {
                object obj = ResourceManager.GetObject("bullet53514100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53514300 {
            get {
                object obj = ResourceManager.GetObject("bullet53514300", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53514700 {
            get {
                object obj = ResourceManager.GetObject("bullet53514700", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53515100 {
            get {
                object obj = ResourceManager.GetObject("bullet53515100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet53515300 {
            get {
                object obj = ResourceManager.GetObject("bullet53515300", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cancel {
            get {
                object obj = ResourceManager.GetObject("Cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cancel22 {
            get {
                object obj = ResourceManager.GetObject("Cancel22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cancel4 {
            get {
                object obj = ResourceManager.GetObject("Cancel4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Connect1 {
            get {
                object obj = ResourceManager.GetObject("Connect1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Connect3 {
            get {
                object obj = ResourceManager.GetObject("Connect3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DebugLog {
            get {
                object obj = ResourceManager.GetObject("DebugLog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DeviceDB {
            get {
                object obj = ResourceManager.GetObject("DeviceDB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Disconnect2 {
            get {
                object obj = ResourceManager.GetObject("Disconnect2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Diverter {
            get {
                object obj = ResourceManager.GetObject("Diverter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Diverter1 {
            get {
                object obj = ResourceManager.GetObject("Diverter1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Down {
            get {
                object obj = ResourceManager.GetObject("Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Down1 {
            get {
                object obj = ResourceManager.GetObject("Down1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Down2 {
            get {
                object obj = ResourceManager.GetObject("Down2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DOWN3 {
            get {
                object obj = ResourceManager.GetObject("DOWN3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ErrorLog {
            get {
                object obj = ResourceManager.GetObject("ErrorLog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Examination {
            get {
                object obj = ResourceManager.GetObject("Examination", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FFUStatus {
            get {
                object obj = ResourceManager.GetObject("FFUStatus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FRONT {
            get {
                object obj = ResourceManager.GetObject("FRONT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GlassDB {
            get {
                object obj = ResourceManager.GetObject("GlassDB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GlassMaint {
            get {
                object obj = ResourceManager.GetObject("GlassMaint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GlassWithdraw {
            get {
                object obj = ResourceManager.GetObject("GlassWithdraw", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GreenFlag {
            get {
                object obj = ResourceManager.GetObject("GreenFlag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Guage {
            get {
                object obj = ResourceManager.GetObject("Guage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Handok {
            get {
                object obj = ResourceManager.GetObject("Handok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Handok_logo {
            get {
                object obj = ResourceManager.GetObject("Handok_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HostLog {
            get {
                object obj = ResourceManager.GetObject("HostLog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HSMSDriver {
            get {
                object obj = ResourceManager.GetObject("HSMSDriver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HSMSMessage {
            get {
                object obj = ResourceManager.GetObject("HSMSMessage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Inform {
            get {
                object obj = ResourceManager.GetObject("Inform", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Inform2 {
            get {
                object obj = ResourceManager.GetObject("Inform2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Inform3 {
            get {
                object obj = ResourceManager.GetObject("Inform3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KeyClosed {
            get {
                object obj = ResourceManager.GetObject("KeyClosed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KeyOpened {
            get {
                object obj = ResourceManager.GetObject("KeyOpened", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LCD {
            get {
                object obj = ResourceManager.GetObject("LCD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LGDisplay {
            get {
                object obj = ResourceManager.GetObject("LGDisplay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LGLS {
            get {
                object obj = ResourceManager.GetObject("LGLS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Log {
            get {
                object obj = ResourceManager.GetObject("Log", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Login5 {
            get {
                object obj = ResourceManager.GetObject("Login5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logo_han {
            get {
                object obj = ResourceManager.GetObject("logo_han", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LPL {
            get {
                object obj = ResourceManager.GetObject("LPL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Maint {
            get {
                object obj = ResourceManager.GetObject("Maint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Maint3 {
            get {
                object obj = ResourceManager.GetObject("Maint3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Maint6 {
            get {
                object obj = ResourceManager.GetObject("Maint6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Offline {
            get {
                object obj = ResourceManager.GetObject("Offline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Offline3 {
            get {
                object obj = ResourceManager.GetObject("Offline3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OK4 {
            get {
                object obj = ResourceManager.GetObject("OK4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Online3 {
            get {
                object obj = ResourceManager.GetObject("Online3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Operation {
            get {
                object obj = ResourceManager.GetObject("Operation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OperationLog {
            get {
                object obj = ResourceManager.GetObject("OperationLog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OPRate {
            get {
                object obj = ResourceManager.GetObject("OPRate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Option {
            get {
                object obj = ResourceManager.GetObject("Option", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Options {
            get {
                object obj = ResourceManager.GetObject("Options", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Options2 {
            get {
                object obj = ResourceManager.GetObject("Options2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PLCAddress {
            get {
                object obj = ResourceManager.GetObject("PLCAddress", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PLCDriver {
            get {
                object obj = ResourceManager.GetObject("PLCDriver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PLCLog {
            get {
                object obj = ResourceManager.GetObject("PLCLog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Power {
            get {
                object obj = ResourceManager.GetObject("Power", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Power2 {
            get {
                object obj = ResourceManager.GetObject("Power2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap processPort {
            get {
                object obj = ResourceManager.GetObject("processPort", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Rackmaster {
            get {
                object obj = ResourceManager.GetObject("Rackmaster", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rail {
            get {
                object obj = ResourceManager.GetObject("rail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RedFlag {
            get {
                object obj = ResourceManager.GetObject("RedFlag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Refresh {
            get {
                object obj = ResourceManager.GetObject("Refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Resize {
            get {
                object obj = ResourceManager.GetObject("Resize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Resize1 {
            get {
                object obj = ResourceManager.GetObject("Resize1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rm {
            get {
                object obj = ResourceManager.GetObject("rm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RMAxis {
            get {
                object obj = ResourceManager.GetObject("RMAxis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RMAxis1 {
            get {
                object obj = ResourceManager.GetObject("RMAxis1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RobotLCS {
            get {
                object obj = ResourceManager.GetObject("RobotLCS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Search {
            get {
                object obj = ResourceManager.GetObject("Search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Search3 {
            get {
                object obj = ResourceManager.GetObject("Search3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shelf {
            get {
                object obj = ResourceManager.GetObject("shelf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StageRate {
            get {
                object obj = ResourceManager.GetObject("StageRate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StageSensor {
            get {
                object obj = ResourceManager.GetObject("StageSensor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StkPort {
            get {
                object obj = ResourceManager.GetObject("StkPort", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StockerSkin {
            get {
                object obj = ResourceManager.GetObject("StockerSkin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap system52158600 {
            get {
                object obj = ResourceManager.GetObject("system52158600", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SystemLog {
            get {
                object obj = ResourceManager.GetObject("SystemLog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TOP {
            get {
                object obj = ResourceManager.GetObject("TOP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap topLogo {
            get {
                object obj = ResourceManager.GetObject("topLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap topLogo1 {
            get {
                object obj = ResourceManager.GetObject("topLogo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap topLogo2 {
            get {
                object obj = ResourceManager.GetObject("topLogo2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TransferDB {
            get {
                object obj = ResourceManager.GetObject("TransferDB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TransferLog {
            get {
                object obj = ResourceManager.GetObject("TransferLog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TurnStage {
            get {
                object obj = ResourceManager.GetObject("TurnStage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UP {
            get {
                object obj = ResourceManager.GetObject("UP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Up1 {
            get {
                object obj = ResourceManager.GetObject("Up1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Up2 {
            get {
                object obj = ResourceManager.GetObject("Up2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UP3 {
            get {
                object obj = ResourceManager.GetObject("UP3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap User2 {
            get {
                object obj = ResourceManager.GetObject("User2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap User20 {
            get {
                object obj = ResourceManager.GetObject("User20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap User5 {
            get {
                object obj = ResourceManager.GetObject("User5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap User51 {
            get {
                object obj = ResourceManager.GetObject("User51", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap User7 {
            get {
                object obj = ResourceManager.GetObject("User7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
