[WMS]
INFO=P1

[Network]
LocalPort=8001
#RemoteIP=98.192.38.205
#RemoteIP=10.99.10.141
RemoteIP=192.100.1.191
#RemoteIP=127.0.0.1
RemotePort=8002

[Property]
RE_DRCT_CNT=3  


[DB]
IP=localhost\SQLEXPRESS
#IP=127.0.0.1
#IP=10.99.43.252
#IP=10.117.3.174
DATABASE = LGLS_MCS_IO
PORT = 5432
USER = LGLS_IO
USER_PW = LGLS_IO
LOGPATH=.\bin\Debug\ECSCOMALog
FILENAME=IOTASK_