//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// Ecs.rc에서 사용되고 있습니다.
//
#define IDC_BUTTON_COPY                 3
#define IDC_BUTTON_PASTE                4
#define IDC_BUTTON_CUT                  5
#define IDC_BUTTON_DELETE               6
#define IDC_BUTTON_SHOW                 7
#define IDC_BUTTON_ERROR_RESET          10
#define IDD_ABOUTBOX                    100
#define IDD_ECS_FORM                    101
#define IDS_PROPSHT_CAPTION             103
#define IDP_SOCKETS_INIT_FAILED         104
#define IDD_MANUAL_PAGE                 105
#define IDD_CONFIG_STD_PAGE             108
#define IDD_CONFIG_SUB1_PAGE            109
#define IDR_MAINFRAME                   128
#define IDR_ECSTYPE                     129
#define IDI_CANCEL1                     130
#define IDB_LOGO_ENG                    132
#define IDI_CANCEL4                     132
#define IDB_LOGO_KOR                    133
#define IDB_SYMBOL                      134
#define IDI_EOAPP                       134
#define IDI_HALLOWEEN1                  135
#define IDI_HALLOWEEN2                  136
#define IDI_KEYMANAGER                  137
#define IDI_SOUND                       138
#define IDI_LAMP1                       140
#define IDI_ZIP1                        141
#define IDB_LOGO_USER                   142
#define IDB_LOGO_MAKER                  143
#define IDI_JPEG                        143
#define IDD_DIALOG_VIEW_SIGNAL          143
#define IDD_LOG_OLD                     144
#define IDI_BALOON                      144
#define IDD_USER_MANAGER                145
#define IDI_CDROM                       146
#define IDD_JOB_ITEM_OLD                146
#define IDD_CV_CTRL                     148
#define IDD_SC_CTRL                     149
#define IDD_OP_BOX_CTRL                 150
#define IDI_WORKGROUP                   152
#define IDI_LOGOFF                      153
#define IDI_HELP                        155
#define IDD_NEW_LOCATION                156
#define IDI_EXPLORER                    156
#define IDD_SC_NEW_LOCATION             156
#define IDD_TEST_LOCATION               156
#define IDI_ABOUT                       157
#define IDD_DIALOG_CYCLE_STEP           159
#define IDI_LEDON                       160
#define IDI_LEDOFF                      161
#define IDI_WEB2                        162
#define IDI_TO_LEFT                     164
#define IDI_TO_RIGHT                    166
#define IDB_BTN_REFRESH                 167
#define IDI_TOOL                        168
#define IDI_OK                          169
#define IDI_RUN                         170
#define IDI_SEARCH                      171
#define IDB_BTN_PASTE                   171
#define IDI_UPDATE                      172
#define IDB_BTN_CUT                     172
#define IDB_BTN_PRINT                   173
#define IDI_IEDOCUMENT                  173
#define IDI_HELP2                       174
#define IDI_USER1                       175
#define IDI_CANCEL                      176
#define IDB_BTN_COPY                    176
#define IDD_PRODUCT_MANAGER             178
#define IDI_ICON_FROG1                  179
#define IDI_NO3                         179
#define IDI_ICON_FROG2                  180
#define IDI_PRODUCT1                    181
#define IDI_ICON_FROG4                  182
#define IDB_ECS_LOGO                    183
#define IDI_LOGIN1                      184
#define IDD_LOGIN                       185
#define IDB_LOGIN                       186
#define IDD_WORKER                      187
#define IDI_CLOSE1                      188
#define IDI_EXIT                        189
#define IDI_BUTTERFLY                   191
#define IDI_USER2                       193
#define IDD_PRODUCT_SETTING             194
#define IDI_BTN_MANUAL                  194
#define IDI_ICON_MANUAL                 194
#define IDI_SAVE                        196
#define IDI_CLIP02                      197
#define IDI_CLOSE                       198
#define IDI_CLIP01                      199
#define IDD_RTV_CTRL                    201
#define IDI_PRODUCT2                    204
#define IDD_PRODUCT_REPORT              205
#define IDD_LOG                         206
#define IDI_REPORT1                     207
#define IDI_USER3                       215
#define IDD_RTV_MANUAL                  215
#define IDI_OPEN                        216
#define IDI_NETWORK1                    218
#define IDI_PLC                         220
#define IDI_LOG1                        222
#define IDI_LOG_ALL                     222
#define IDI_LOG2                        223
#define IDI_LOG_JOB                     223
#define IDI_PRINT1                      225
#define IDI_LOG3                        226
#define IDI_LOG_MODE                    226
#define IDI_LOG4                        227
#define IDI_LOG_EVENT                   227
#define IDI_LOG5                        228
#define IDI_LOG_ERROR                   228
#define IDI_LOG6                        229
#define IDI_LOG_DEBUG                   229
#define IDI_FIND                        232
#define IDI_PRINT                       237
#define IDD_SC_MANUAL                   238
#define IDI_ICON_HOME                   239
#define IDI_ICON_COMPLETE               241
#define IDI_LINE                        245
#define IDD_DIALOG1                     246
#define IDI_ICON_MODIFY                 246
#define IDI_PC                          247
#define IDI_KEY                         249
#define IDI_PRODUCT                     250
#define IDI_IDCARD                      251
#define IDI_PRODUCT3                    252
#define IDI_ICON_FROG3                  253
#define IDB_BITMAP1                     253
#define IDI_ICON_ESTOP                  256
#define IDI_USER                        257
#define IDI_BOARD                       259
#define IDI_ICON_CUT                    263
#define IDI_ICON_PASTE                  264
#define IDI_ICON_COPY                   265
#define IDB_ECS_EQUIP                   268
#define IDI_LOG                         269
#define IDI_USER4                       271
#define IDD_LOADER_CTRL                 281
#define IDI_CUT                         283
#define IDI_EX_INFO                     284
#define IDI_EX_CAUTION                  285
#define IDI_EX_ERROR                    286
#define IDI_BOX1                        287
#define IDI_BOX2                        288
#define IDI_BOX3                        289
#define IDI_BOX4                        290
#define IDI_BOX5                        291
#define IDI_BOX6                        292
#define IDI_BOX7                        293
#define IDD_DATA_SETTING                294
#define IDD_UNLOADER_CTRL               295
#define IDD_CV_MULGUN_CTRL              296
#define IDD_JOB                         297
#define IDD_JOB_PROGRESS                298
#define IDI_ICON_RETURN                 302
#define IDD_RTV_CONFIG                  303
#define IDD_JOB_PLAN                    305
#define IDD_USER                        308
#define IDI_ICON1                       311
#define IDI_WORKER1                     313
#define IDI_WORKER2                     314
#define IDI_BASKET                      315
#define IDI_JOB_PLAN                    316
#define IDI_JOB_RESULT                  317
#define IDD_PORT_ETHERNET               318
#define IDD_PORT_SERIAL                 319
#define IDI_ICON_LEDON                  321
#define IDI_ICON_LEDOFF                 322
#define IDI_COPY                        323
#define IDI_PASTE                       324
#define IDI_JOB_ALL                     325
#define IDI_JOB_ERROR                   326
#define IDI_JOB_NEW                     327
#define IDI_JOB_PROGRESS                328
#define IDI_JOB_COMPLETE                329
#define IDI_TO_EJECT                    331
#define IDI_TO_X                        333
#define IDB_BITMAP2                     334
#define IDI_TO_BOTH                     335
#define IDD_TRACK_IO                    336
#define IDD_RTV_IO                      337
#define IDI_NETWORK2                    338
#define IDD_ECS_FORM1                   338
#define IDD_CONFIG_SUB2_PAGE            338
#define IDD_ECS_FORM2                   339
#define IDI_IO                          340
#define IDI_BOX8                        341
#define IDI_DOC1                        342
#define IDI_ICON2                       344
#define IDI_CLASSES1                    346
#define IDI_CANCEL3                     347
#define IDI_RAZOR                       349
#define IDI_OK3                         350
#define IDI_OPEN01                      351
#define IDD_LGV_CTRL                    353
#define IDD_JOB_OFFLINE                 357
#define IDD_DIALOG2                     359
#define IDD_JOB_ITEM                    359
#define IDD_LGV_MANUAL                  362
#define IDC_CURSOR1                     364
#define IDD_RACK_CONFIG                 367
#define IDC_CURSOR2                     369
#define IDC_CURSOR3                     370
#define IDC_CURSOR4                     371
#define IDD_DISPLAY                     372
#define IDB_ECS_RGV                     385
#define IDB_ECS_CV                      386
#define IDR_TOOLBAR1                    423
#define IDR_TOOLBAR0                    424
#define IDI_ICON_LOG_ERROR              425
#define IDI_ICON_LOG_QUESTION           426
#define IDI_ICON_LOG_WARNING            427
#define IDI_ICON_LOG_INFO               428
#define IDD_WARNING_DLG                 430
#define IDI_ICON_LIGHTBULB              431
#define IDD_RFID_CTRL_OLD               431
#define IDD_BCR_CTRL                    432
#define IDI_CLASSES2                    432
#define IDD_LIFTER_CTRL                 433
#define IDI_CLASSES3                    433
#define IDD_LIFTER_MANUAL               434
#define IDI_CLASSES4                    434
#define IDD_DISPLAY_CTRL                435
#define IDI_CLASSES5                    435
#define IDD_BCR_CTRL1                   436
#define IDD_RFID_CTRL                   436
#define IDI_CLASSES6                    436
#define IDI_LOG_ALARM                   437
#define IDD_CV_CTRL1                    437
#define IDD_SC_CTRL1                    438
#define IDI_CLIP03                      438
#define IDD_RTV_CTRL1                   439
#define IDD_LIFTER_CTRL1                440
#define IDD_SC_NEW_LOCATION2            441
#define IDD_TEST_LOCATION1              441
#define IDD_JOB_TEST                    442
#define IDD_SC_PAIR_CTRL                443
#define IDD_SC_PAIR_MANUAL              445
#define IDR_LOGGINGBAR                  446
#define IDD_SC_PAIR_NEW_LOCATION        446
#define IDD_SC_NEW_LOCATION1            447
#define IDR_TOOLBAR2                    447
#define IDR_TOOLBAR3                    448
#define IDR_LOGGING                     449
#define IDB_SEARCH                      490
#define IDD_SYS_USER_MANAGER            523
#define IDC_BUTTON_CHANGE               1000
#define IDC_BTN_MODE                    1001
#define IDC_BTN_INIT                    1002
#define IDC_STATIC_DATE                 1003
#define IDC_STATIC_DATE_TIME            1003
#define IDC_TAB_CYCLE_STEP              1003
#define IDC_COMBO_DEPART_STATION        1004
#define IDC_LABEL_CUR_STEP              1006
#define IDC_BTN_EXECUTE                 1008
#define IDC_LIST_LOG                    1009
#define IDC_MSFLXGRID_SIG_ECS2PLC       1009
#define IDC_MSFLXGRID_SIG_PLC2ECS       1010
#define IDC_LABEL1                      1011
#define IDC_LABEL2                      1012
#define IDC_COMBO_POSITION              1014
#define IDC_COMBO_JOB_TYPE              1014
#define IDC_EDIT_MODE                   1014
#define IDC_COMBO_DEST                  1014
#define IDC_LABEL4                      1014
#define IDC_COMBO_START                 1015
#define IDC_LABEL5                      1015
#define IDC_TAB_LOG                     1016
#define IDC_COMBO_START_WH              1016
#define IDC_COMBO_USEFORK               1016
#define IDC_LABEL6                      1016
#define IDC_COMBO_START_BANK            1016
#define IDC_SPIN_FROM                   1017
#define IDC_LABEL7                      1017
#define IDC_COMBO_START_BAY             1017
#define IDC_SPIN_TO                     1018
#define IDC_LABEL9                      1018
#define IDC_COMBO_START_LEVEL           1018
#define IDC_BUTTON_CANCEL               1019
#define IDC_COMBO_GEN                   1019
#define IDC_COMBO_GEN_CODE              1019
#define IDC_LABEL10                     1019
#define IDC_BUTTON_FIND                 1020
#define IDC_BUTTON_COMPLETE             1020
#define IDC_COMBO_WAREHOUSE             1020
#define IDC_BUTTON_EMERGENCY            1021
#define IDC_CHECK_EVENT                 1024
#define IDC_EDIT_LUGG_ID                1024
#define IDC_EDIT_CONTEXT                1024
#define IDC_CHECK_ERROR                 1025
#define IDC_CHECK_CONNECT               1026
#define IDC_CHECK_RETRY                 1027
#define IDC_CHECK_JOB_ID                1027
#define IDC_CHECK_LUGG_ID               1027
#define IDC_CHECK_DEBUG                 1028
#define IDC_EDIT_FROM                   1028
#define IDC_CHECK_BEEP                  1029
#define IDC_EDIT_FROM2                  1029
#define IDC_EDIT_RGV_JOB_START_POS      1029
#define IDC_BUTTON_PRINT                1030
#define IDC_CHECK_EVENT2                1030
#define IDC_CHECK_MODE                  1030
#define IDC_CHECK_ALARM                 1030
#define IDC_EDIT_FROM3                  1030
#define IDC_EDIT_RGV_JOB_DEST_POS       1030
#define IDC_BUTTON_COLOR_RESET          1031
#define IDC_BUTTON_FILE                 1031
#define IDC_EDIT_FROM4                  1031
#define IDC_EDIT_RGV_JOB_PRODUCT        1031
#define IDC_BUTTON_PATH_RESET           1032
#define IDC_EDIT_DATE                   1032
#define IDC_EDIT_RGV_JOB_STATUS         1032
#define IDC_BUTTON_REFRESH              1033
#define IDC_EDIT_FROM5                  1033
#define IDC_EDIT_RGV_JOB_WEIGHT         1033
#define IDC_BUTTON_REPORT               1034
#define IDC_BTN_JOB_DETAIL              1034
#define IDC_BUTTON_STATUS_REPORT        1034
#define IDC_BTN_TRACK_IO                1035
#define IDC_BUTTON_CONFIRM              1038
#define IDC_CHECK_IS_PORT               1038
#define IDC_CHECK_PAIR_JOB              1039
#define IDC_EDIT_TS_ADDR                1040
#define IDC_EDIT_TS_PORT                1041
#define IDC_EDIT_LUGG_NUM               1041
#define IDC_EDIT_ECS_PORT               1042
#define IDC_EDIT_TRACK_NUM              1042
#define IDC_EDIT_TIME                   1042
#define IDC_EDIT_START_WH               1042
#define IDC_EDIT_LUGG_NUM2              1042
#define IDC_EDIT_CV_STATUS              1043
#define IDC_EDIT_START_POS              1043
#define IDC_EDIT_START_STN              1043
#define IDC_EDIT_EDIT_START             1044
#define IDC_EDIT_DEST_POS               1044
#define IDC_EDIT_START                  1044
#define IDC_EDIT_SCAN_READY             1044
#define IDC_EDIT_SIZE                   1044
#define IDC_EDIT_INTERNAL_LUGG_NUM      1045
#define IDC_EDIT_REPORT_TIME            1045
#define IDC_EDIT_DEST_WH                1045
#define IDC_EDIT_START_HOME_STAND       1046
#define IDC_EDIT_JOB_START_HS           1046
#define IDC_EDIT_REPORT_TYPE            1046
#define IDC_EDIT_JOB_START_ST           1046
#define IDC_EDIT_DEST_STN               1046
#define IDC_EDIT_START_POS2             1046
#define IDC_EDIT_REQ_ERR                1046
#define IDC_COMBO_STATUS                1047
#define IDC_EDIT_DEST_POS2              1047
#define IDC_EDIT_DIAGNOSIS              1048
#define IDC_EDIT_ERR_INFO               1048
#define IDC_EDIT_DEPART_HS              1048
#define IDC_BUTTON_MANUAL_STO           1049
#define IDC_EDIT_TYPE                   1049
#define IDC_EDIT_UPDATE_TIME            1049
#define IDC_EDIT_INTERNAL_LUGG_NUM2     1049
#define IDC_BUTTON_WRITE                1050
#define IDC_EDIT_DEST_HOME_STAND        1050
#define IDC_EDIT_JOB_DEST_HS            1050
#define IDC_EDIT_PRODID                 1050
#define IDC_EDIT_JOB_DEST_ST            1050
#define IDC_EDIT_JOB_PROGRESS           1051
#define IDC_EDIT_PRODINFO               1051
#define IDC_EDIT_COMMANDTIME            1052
#define IDC_COMBO_DESTINATION           1053
#define IDC_EDIT_PRODGEN                1053
#define IDC_COMBO_DEST_TRACK            1053
#define IDC_STATIC_POS3                 1054
#define IDC_STATIC_POS4                 1055
#define IDC_EDIT_START_WAREHOUSE        1055
#define IDC_EDIT_JOB_TYPE               1056
#define IDC_EDIT_DEST_WAREHOUSE         1056
#define IDC_STATIC_POS7                 1057
#define IDC_EDIT_SC_SC_MODE             1057
#define IDC_EDIT_SC_MODE                1057
#define IDC_EDIT_ARRIVE_HS              1057
#define IDC_EDIT_PRODLOAD               1058
#define IDC_EDIT_STARTPOS               1058
#define IDC_EDIT_FORK_POS               1058
#define IDC_EDIT_SC_RC_MODE             1059
#define IDC_EDIT_DESTPOS                1059
#define IDC_EDIT_RC_MODE                1059
#define IDC_EDIT_CRATE_STATUS           1059
#define IDC_EDIT_FORK_STATUS            1060
#define IDC_EDIT_BARCODE                1060
#define IDC_EDIT_COMPLETE_NUM           1061
#define IDC_EDIT_LINE_INFO              1061
#define IDC_EDIT_PREV_STATUS            1061
#define IDC_STATIC_POS6                 1061
#define IDC_EDIT_SC_ACTIVE              1062
#define IDC_EDIT_COMPANY                1062
#define IDC_EDIT_JOB_COUNT              1062
#define IDC_EDIT_FORK_STATUS2           1062
#define IDC_LIST_COMM1                  1063
#define IDC_EDIT_NUM                    1063
#define IDC_EDIT_HORIZONTAL_POS         1063
#define IDC_EDIT_PROD_INFO              1063
#define IDC_EDIT_PASSWORD               1063
#define IDC_LIST_COMM2                  1064
#define IDC_EDIT_TO                     1064
#define IDC_EDIT_JISANG_MODE            1064
#define IDC_EDIT_DEST                   1064
#define IDC_EDIT_SC_NUM                 1064
#define IDC_EDIT_CRATE_KIND             1064
#define IDC_EDIT_RC_STATUS2             1064
#define IDC_EDIT_RC_STATUS              1064
#define IDC_LBL_HORIZONTAL_ERROR        1064
#define IDC_EDIT_STATUS                 1065
#define IDC_EDIT_SC_STATUS              1065
#define IDC_EDIT_PAIR_LUGG              1065
#define IDC_FPSPREAD1                   1065
#define IDC_EDIT_JOB_STATUS             1066
#define IDC_LBL_VERTICAL_ERROR          1066
#define IDC_EDIT_ERROR_STATUS           1066
#define IDC_EDIT_PRODUCT                1067
#define IDC_BUTTON_RESET                1067
#define IDC_EDIT_JOB_START_POS          1067
#define IDC_LBL_FORK_ERROR              1067
#define IDC_STATIC_POS9                 1067
#define IDC_EDIT_PROD_ORIGIN            1068
#define IDC_BUTTON_ESTOP                1068
#define IDC_EDIT_TAGID                  1068
#define IDC_LBL_CYCLE_STEP              1068
#define IDC_EDIT_PROD_UNIT              1069
#define IDC_EDIT_VERTICAL_POS           1069
#define IDC_EDIT_REQUEST_TAGID          1069
#define IDC_LBL_HORZ_POS                1069
#define IDC_EDIT_PROD_NO                1070
#define IDC_CHECK_SUSPEND               1070
#define IDC_EDIT_JOB_PROD_CNT           1070
#define IDC_CHECK_STORE                 1070
#define IDC_EDIT_REPORT_TAGID           1070
#define IDC_CHECK_SUSPENT_STORE         1070
#define IDC_LBL_VERT_POS                1070
#define IDC_EDIT_STN_MODE               1071
#define IDC_EDIT_TRACK_MODE             1071
#define IDC_CHECK_RETRIEVE              1071
#define IDC_CHECK_SUSPEND_RETRIEVE      1071
#define ID_BUTTON_SAVE                  1072
#define IDC_EDIT_PRODUCT2               1072
#define IDC_BUTTON_CALL_TO_HOME         1072
#define IDC_CHECK_SUSPEND_HS            1072
#define IDC_CHECK_DEADLOCK              1072
#define IDC_CHECK_JOB                   1073
#define IDC_SCCTRL6                     1073
#define IDC_EDIT_BATCH                  1073
#define IDC_BUTTON_STOP                 1073
#define IDC_EDIT_JOB_FORCE_COMPLETE     1073
#define IDC_EDIT_JOB_EQUIP              1073
#define IDC_BUTTON_DUAL_STORE           1073
#define IDC_SCCTRL7                     1074
#define IDC_BUTTON_ACTIVE               1074
#define IDC_EDIT_TRACK_PRODUCT          1074
#define IDC_EDIT_COMPLETE               1075
#define IDC_EDIT_JOB_PRODUCT            1075
#define IDC_EDIT_JOB_START_POS2         1075
#define IDC_CHECK_SUSPEND_RACKTORACK    1075
#define IDC_EDIT_JOB_LINE               1076
#define IDC_EDIT_JOB_INFO               1076
#define IDC_EDIT_SC_SPEED               1076
#define IDC_EDIT_JOB_DEPART_POS         1076
#define IDC_EDIT_JOB_START_STN          1076
#define IDC_EDIT_JOB_STATUS2            1076
#define IDC_BUTTON_CUT_JOBINFO          1076
#define IDC_EDIT_JOB_LINE2              1077
#define IDC_EDIT_JOB_LOT                1077
#define IDC_EDIT_JOB_PRODUCT2           1077
#define IDC_EDIT_JOB_TYPE2              1077
#define IDC_EDIT_SC_CYCLE1              1077
#define IDC_EDIT_JOB_JBATCH             1078
#define IDC_EDIT_JOB_PRODUCT3           1078
#define IDC_EDIT_ERROR_STATUS2          1078
#define IDC_BUTTON_REDO_CYCLE           1078
#define IDC_EDIT_JOB_MBATCH             1079
#define IDC_CHECK_RTR                   1079
#define IDC_EDIT_SC_CYCLE2              1079
#define IDC_BUTTON_CSTOP                1080
#define IDC_EDIT_SC_CYCLE3              1080
#define IDC_BUTTON1                     1081
#define IDC_BUTTON_REQUEST_TRANSPORT    1081
#define IDC_BUTTON_DOOR_IN1             1081
#define IDC_BUTTON_CREATE               1081
#define IDC_BUTTON_POWER                1081
#define IDC_BTN_DELETE                  1082
#define IDC_BTN_RESET4                  1082
#define IDC_BUTTON_REQUEST_DELETE       1082
#define IDC_BUTTON_VIEW_SIG             1082
#define IDC_BTN_RESET1                  1082
#define IDC_BTN_UPDATE                  1083
#define IDC_BTN_RESET5                  1083
#define IDC_BUTTON_REQUEST_MODIFY       1083
#define IDC_BUTTON_REDO_CYCLESTEP       1083
#define IDC_BUTTON_CYCLE_STEP           1083
#define IDC_BUTTON_REQUEST_SUSPEND      1083
#define IDC_BTN_ALTER_LOC               1083
#define IDC_BTN_REMOVE                  1084
#define IDC_BTN_RESET6                  1084
#define IDC_BUTTON_REQUEST_STATUS       1084
#define IDC_BTN_ARRIVE                  1084
#define IDC_BUTTON_CYCLE_FLOW           1084
#define IDC_USER_SAVE                   1084
#define IDC_BTN_RTR_ORDER               1084
#define IDC_BTN_IN_DOOR_CLOSE           1085
#define IDC_BTN_RESET3                  1085
#define IDC_BUTTON_REPORT_DOOR_STATUS   1085
#define IDC_BUTTON_DOOR_IN2             1085
#define IDC_EDIT_SC_CYCLE4              1085
#define IDC_BTN_ATA_ORDER               1085
#define IDC_BTN_OUT_DOOR_CLOSE          1086
#define IDC_BTN_RESET7                  1086
#define IDC_BTN_RESET2                  1086
#define IDC_BUTTON_DOOR_IN3             1086
#define IDC_EDIT_SC_CYCLE               1086
#define IDC_BTN_SITE_ORDER              1086
#define IDC_BTN_IN_REQUEST              1087
#define IDC_BUTTON_DOOR_IN4             1087
#define IDC_BTN_RESET8                  1087
#define IDC_BTN_OUT_REQUEST             1088
#define IDC_BUTTON_DOOR_OUT1            1088
#define IDC_BTN_IN_START                1089
#define IDC_BUTTON_DOOR_OUT2            1089
#define IDC_BTN_OUT_START               1090
#define IDC_BUTTON_DOOR_OUT3            1090
#define IDC_LIST1                       1091
#define IDC_LIST                        1091
#define IDC_BTN_IN_COMPLETE             1091
#define IDC_LIST_LGV_JOB                1091
#define IDC_BUTTON_DOOR_OUT4            1091
#define IDC_EDIT1                       1092
#define IDC_EDIT_LOCATION               1092
#define IDC_LIST_WORKER                 1092
#define IDC_EDIT_INTERNAL_JOB_TYPE      1092
#define IDC_EDT_PORT                    1092
#define IDC_EDT_DEVICE                  1092
#define IDC_BTN_OUT_COMPLETE            1092
#define IDC_EDT_PINFO4                  1092
#define IDC_EDIT_SERVER_STATUS          1092
#define IDC_EDIT_DEPART                 1092
#define IDC_EDIT_START_LOCATION         1092
#define IDC_EDIT_TRANSPORT_ID           1092
#define IDC_DEVICE_KIND                 1092
#define IDC_EDIT_DISPLAY                1092
#define IDC_EDIT2                       1093
#define IDC_EDT_NAME                    1093
#define IDC_EDIT_CLIENT_STATUS          1093
#define IDC_EDIT_ARRIVE                 1093
#define IDC_EDIT_DEST_LOCATION          1093
#define IDC_DEVICE_NO                   1093
#define IDC_EDIT_LOCATION2              1093
#define IDC_EDIT_STATION                1093
#define IDC_EDIT_CYCLE_STEP             1093
#define IDC_COMBO1                      1094
#define IDC_EDIT3                       1094
#define IDC_CBX_LINE                    1094
#define IDC_EDT_IP                      1094
#define IDC_CBX_PLAN4                   1094
#define IDC_CBX_DEPART                  1094
#define IDC_CBX_ARRIVE_HS               1094
#define IDC_COMBO_DOOR                  1094
#define IDC_COMBO_DEPART                1094
#define IDC_COMBO_START_STATION         1094
#define IDC_COMBO_JOB_STATUS            1094
#define IDC_COMBO_JOB_CRATE_STATUS      1094
#define IDC_ERROR_KIND                  1094
#define IDC_EDIT4                       1095
#define IDC_CBX_DATE                    1095
#define IDC_CBX_ARRIVE                  1095
#define IDC_EDT_PINFO5                  1095
#define IDC_EDT_RECV_TIMEOUT            1095
#define IDC_EDIT_SEQNO_SEND             1095
#define IDC_COMBO_ARRIVE                1095
#define IDC_COMBO_DEST_STATION          1095
#define IDC_COMBO_PRIORITY              1095
#define IDC_COMBO_STATION               1095
#define IDC_ERROR_CODE                  1095
#define IDC_COMBO5                      1095
#define IDC_EDIT5                       1096
#define IDC_COMBO2                      1096
#define IDC_CBX_MULGUN                  1096
#define IDC_CBX_PLAN5                   1096
#define IDC_EDIT_SEQNO_RECV             1096
#define IDC_COMBO_START_WAREHOUSE       1096
#define IDC_COMBO_DEPART_HS             1096
#define IDC_LUGG_NUM                    1096
#define IDC_COMBO6                      1096
#define IDC_EDIT6                       1097
#define IDC_CBX_START_POS               1097
#define IDC_CBX_PLAN6                   1097
#define IDC_EDIT_AGV_MODE               1097
#define IDC_COMBO_DEST_WAREHOUSE        1097
#define IDC_COMBO_ARRIVE_HS             1097
#define IDC_LOCATION                    1097
#define IDC_COMBO3                      1098
#define IDC_EDT_PINFO6                  1098
#define IDC_EDIT_AGV_STATUS             1098
#define IDC_STATION                     1098
#define IDC_EDIT7                       1099
#define IDC_CBX_JOB_STATUS              1099
#define IDC_EDT_LOT_NO5                 1099
#define IDC_EDIT_AGV_POSITION           1099
#define IDC_BTN_COMPLETE                1099
#define IDC_IN_OUT_PUT                  1099
#define IDC_BTN_SAVE                    1100
#define IDC_EDIT8                       1100
#define IDC_EDT_JBATCH_NO5              1100
#define IDC_BTN_ADD2                    1100
#define IDC_BTN_ADD                     1100
#define IDC_WEIGHT                      1100
#define IDC_BTN_EXCEL                   1100
#define IDC_EDIT9                       1101
#define IDC_CBX_MULGUN_ORDER            1101
#define IDC_EDT_PLAN_CNT5               1101
#define IDC_EDIT_MESSAGE_SEND           1101
#define IDC_DOOR_STATUS                 1101
#define IDC_BTN_REPORT                  1102
#define IDC_EDIT10                      1102
#define IDC_EDT_PCODE6                  1102
#define IDC_EDIT_LOAD_STATUS            1102
#define IDC_OPEN_REQUEST                1102
#define IDC_COMBO4                      1103
#define IDC_EDT_PNAME5                  1103
#define IDC_EDIT_MESSAGE_RECV           1103
#define IDC_REQUST_STATION              1103
#define IDC_EDIT11                      1104
#define IDC_EDT_LOT_NO6                 1104
#define IDC_EDIT_BATTERY_STATUS         1104
#define IDC_OPEN_ACCEPT                 1104
#define IDC_EDIT12                      1105
#define IDC_EDT_JBATCH_NO6              1105
#define IDC_EDIT_BATTERY_CHARGE         1105
#define IDC_EDIT_ERROR_CODE             1105
#define IDC_CLOSE_REPORT                1105
#define IDC_EDIT13                      1106
#define IDC_EDT_PLAN_CNT6               1106
#define IDC_EDIT_AGV_TRANPORT_ID        1106
#define IDC_RGV_STATUS                  1106
#define IDC_EDT_PNAME6                  1107
#define IDC_PLC_GROUP                   1107
#define IDC_PLC_COMM                    1107
#define IDC_CBX_PLAN3                   1108
#define IDC_EDIT_AGV_JOB_STATUS         1108
#define IDC_EDIT_AGV_ERROR              1108
#define IDC_DOOR_STATUS2                1108
#define IDC_EDT_PINFO3                  1109
#define IDC_EDIT_DOOR_STATUS            1109
#define IDC_OPEN_REQUEST2               1109
#define IDC_EDT_PCODE3                  1110
#define IDC_OPEN_ACCEPT2                1110
#define IDC_EDT_PNAME3                  1111
#define IDC_CLOSE_REPORT2               1111
#define IDC_EDT_LOT_NO3                 1112
#define IDC_RGV_STATUS2                 1112
#define IDC_EDT_JBATCH_NO3              1113
#define IDC_REQUST_LAMP                 1113
#define IDC_EDT_PLAN_CNT3               1114
#define IDC_WORKING_LUGG1               1114
#define IDC_CBX_PLAN2                   1115
#define IDC_DUAL_STO_LOC                1115
#define IDC_EDT_PINFO2                  1116
#define IDC_RECEIVE_STATUS              1116
#define IDC_EDT_PCODE2                  1117
#define IDC_EDT_FROM_LOC                1117
#define IDC_EDT_PNAME7                  1118
#define IDC_EDT_PNAME2                  1118
#define IDC_EDT_TO_LOC                  1118
#define IDC_EDT_LOT_NO7                 1119
#define IDC_EDT_LOT_NO2                 1119
#define IDC_DUAL_STO_LUGG               1119
#define IDC_EDT_JBATCH_NO7              1120
#define IDC_EDT_JBATCH_NO2              1120
#define IDC_EDT_FROM_STN1               1120
#define IDC_EDT_PLAN_CNT7               1121
#define IDC_EDT_PLAN_CNT2               1121
#define IDC_EDT_TO_STN1                 1121
#define IDC_WORKING_LUGG2               1122
#define IDC_EDT_FROM_STN2               1123
#define IDC_EDT_TO_STN2                 1124
#define IDC_BUTTON_SAVE                 1144
#define IDC_BTN_FIND1                   1147
#define IDC_BTN_FIND4                   1147
#define IDC_BTN_FIND5                   1148
#define IDC_LIST_USER                   1149
#define IDC_BTN_FIND6                   1149
#define IDC_LIST_PRODUCT                1150
#define IDC_BTN_FIND7                   1150
#define IDC_BTN_FIND3                   1150
#define IDC_BTN_DEL                     1151
#define IDC_BTN_FIND8                   1151
#define IDC_BTN_FIND2                   1151
#define IDC_EDT_DRIVER                  1152
#define IDC_EDT_SERVER                  1153
#define IDC_EDT_USERID                  1154
#define IDC_EDT_PORT_ECS                1154
#define IDC_EDT_USERPW                  1155
#define IDC_EDT_WEIGHT_VALUE            1155
#define IDC_EDIT_LOADER_NUM             1156
#define IDC_EDT_FONT_SIZE               1156
#define IDC_EDIT_LOADER_MODE            1157
#define IDC_EDT_BUFFER_CNT              1157
#define IDC_EDIT_LOADER_ERRSTATUS       1158
#define IDC_EDT_COMPLETE_CNT            1158
#define IDC_BTN_LOADER_CAPACITY         1159
#define IDC_EDT_FONT_SIZE3              1159
#define IDC_EDIT_LOADER_ACTIVE          1160
#define IDC_BTN_LOADER_COUNT            1161
#define IDC_BTN_LOADER_START            1162
#define IDC_BTN_LOADER_FORCE            1163
#define IDC_EDIT_CAPACITY               1164
#define IDC_EDIT_COUNT_PER_TRAY         1165
#define IDC_EDIT_TRAY_PER_BASKET        1166
#define IDC_EDIT_TRAY_ORDER             1167
#define IDC_EDIT_LOADING_CNT_PER_TRAY   1168
#define IDC_EDIT_LOADING_CNT_PER_BASKET 1169
#define IDC_EDIT_LOADER_STATUS          1170
#define IDC_EDIT_LOADER_MSG             1171
#define IDC_BTN_LOADER_REFRESH          1172
#define IDC_STATIC_LOADER_STATUS        1173
#define IDC_EDIT_DATA                   1174
#define IDC_EDIT_LOADER_FORCE           1174
#define IDC_EDIT_UNLOADING_CNT_PER_TRAY 1175
#define IDC_BTN_LOADER_JOB_PLAN         1175
#define IDC_EDIT_UNLOADING_CNT_PER_BASKET 1176
#define IDC_EDIT_LOADER_LOT_STATUS      1176
#define IDC_STATIC_UNLOADER_STATUS      1177
#define IDC_EDIT_LOADER_LOT_BEGIN       1177
#define IDC_EDIT_UNLOADER_STATUS        1178
#define IDC_EDIT_LOADER_LOT_END         1178
#define IDC_EDIT_UNLOADER_MODE          1179
#define IDC_EDIT_LOADER_LOT_TIME        1179
#define IDC_EDIT_UNLOADER_ERRSTATUS     1180
#define IDC_EDIT_UNLOADER_ACTIVE        1181
#define IDC_EDIT_UNLOADER_MSG           1182
#define IDC_BTN_UNLOADER_CAPACITY       1183
#define IDC_BTN_UNLOADER_COUNT          1184
#define IDC_BTN_UNLOADER_START          1185
#define IDC_BTN_UNLOADER_REFRESH        1186
#define IDC_EDIT_UNLOADER_NUM           1187
#define IDC_EDIT_EQUIP_NUM              1188
#define IDC_EDIT_UNLOADER_FORCE         1188
#define IDC_EDIT_IN_REQUEST             1189
#define IDC_EDIT_UNLOADER_LOT_STATUS    1189
#define IDC_EDIT_OUT_COMPLETE           1190
#define IDC_EDIT_UNLOADER_LOT_BEGIN     1190
#define IDC_BTN_PERMIT_IN               1191
#define IDC_EDIT_UNLOADER_LOT_END       1191
#define IDC_BTN_PERMIT_START            1192
#define IDC_EDIT_UNLOADER_LOT_TIME      1192
#define IDC_BTN_REFRESH                 1193
#define IDC_EDIT_UNLOADER_WARNNING      1193
#define IDC_EDIT_ERROR                  1194
#define IDC_TAB_JOB                     1195
#define IDC_EDIT_PRODUCT_ID             1195
#define IDC_LIST_JOB                    1196
#define IDC_EDIT_INSTALLTIME            1196
#define IDC_BTN_SELECT_DB               1197
#define IDC_BTN_JOB_PLAN                1198
#define IDC_TAB_MANUAL                  1198
#define IDC_LOGIN_USER_ID               1198
#define IDC_EDT_JOB_PLAN                1199
#define IDC_LOGIN_PASSWORD              1199
#define IDC_LIST_JOB2                   1199
#define IDC_LIST_THIS_LOGIC_JOB         1199
#define IDC_EDIT_RGV_NUM                1200
#define IDC_EDT_JOB_RESULT              1200
#define IDC_EDT_NEW_PASSWORD            1200
#define IDC_EDIT_RGV_MODE               1201
#define IDC_BTN_LUGG_NUM                1201
#define IDC_EDT_PASSWORD_CONFIRM        1201
#define IDC_EDT_LUGG_NUM                1202
#define IDC_CBX_JOB_TYPE                1203
#define IDC_EDIT_PROD_INFO1             1203
#define IDC_CBX_FILTER_JOB_TYPE         1203
#define IDC_EDIT_STO_HOME_STAND         1203
#define IDC_BTN_START_POS               1204
#define IDC_EDT_BATCH_INFO              1204
#define IDC_EDIT_PROD_INFO2             1204
#define IDC_CBX_SC                      1204
#define IDC_CBX_FILTER_START_STATION    1204
#define IDC_EDIT_JOB_DEST_POS           1204
#define IDC_EDIT_RET_HOME_STAND         1204
#define IDC_CBX_DEST_POS                1205
#define IDC_EDT_BATCH_COUNT             1205
#define IDC_EDIT_ECS_JOB_TYPE           1205
#define IDC_CBX_FILTER_DEST_STATION     1205
#define IDC_EDIT_PROD_INFO3             1205
#define IDC_BTN_JOB_STATUS              1206
#define IDC_CBX_FORCE_COMPLETE          1206
#define IDC_EDIT_ECS_JOB_TYPE2          1206
#define IDC_CBX_FILTER_IDLE_JOB         1206
#define IDC_EDT_ERROR_STATUS            1207
#define IDC_CBX_FIFO_STATUS             1207
#define IDC_EDIT_JOB_DEST_POS2          1207
#define IDC_BTN_MULGUN_ORDER            1208
#define IDC_EDT_DEPART_TRACK            1209
#define IDC_BTN_ARRIVE_TRACK            1210
#define IDC_EDT_ARRIVE_TRACK            1211
#define IDC_EDT_JOB_RESULT2             1212
#define IDC_BTN_FINE                    1212
#define IDC_EDT_JOB_RESULT3             1213
#define IDC_CHK_AUTO_REFRESH            1213
#define IDC_EDT_JOB_RESULT4             1214
#define IDC_EDT_COUNT                   1214
#define IDC_EDT_JOB_RESULT5             1215
#define IDC_BTN_FILTER                  1215
#define IDC_BTN_EDIT                    1216
#define IDC_EDT_LINE_NO                 1216
#define IDC_BTN_CANCEL                  1216
#define IDC_STATIC_SUSPEND_HS           1217
#define IDC_EDT_LOT_NO                  1217
#define IDC_BTN_COPY                    1217
#define IDC_RADIO_RTV12                 1218
#define IDC_EDT_JBATCH_NO               1218
#define IDC_RADIO_RTV1                  1219
#define IDC_EDT_MBATCH_NO               1219
#define IDC_BTN_PAIR                    1219
#define IDC_RADIO_RTV2                  1220
#define IDC_EDT_LOADER_NO               1220
#define IDC_EDT_TOTAL_UNLOADING_COUNT   1220
#define IDC_RADIO_RTV34                 1221
#define IDC_EDT_REFRESH_TIME            1221
#define IDC_EDT_MULGUN_NO               1221
#define IDC_RADIO_RTV3                  1222
#define IDC_BTN_SET4                    1222
#define IDC_EDT_UNLOADER_NO             1222
#define IDC_RADIO_RTV4                  1223
#define IDC_BTN_SET5                    1223
#define IDC_EDT_PCOUNT                  1223
#define IDC_BTN_SET6                    1224
#define IDC_EDT_PNAME                   1224
#define IDC_EDT_PCODE4                  1225
#define IDC_EDT_PCODE                   1225
#define IDC_EDT_PNAME4                  1226
#define IDC_EDT_LUGG_NO                 1226
#define IDC_EDT_LOT_NO4                 1227
#define IDC_EDT_JOB_TYPE                1227
#define IDC_EDT_JBATCH_NO4              1228
#define IDC_EDT_START_POS               1228
#define IDC_EDT_TOTAL_LOADING_COUNT     1228
#define IDC_EDT_PLAN_CNT4               1229
#define IDC_EDT_RTV_DEPART              1229
#define IDC_EDT_TOTAL_MULGUN_COUNT      1229
#define IDC_EDT_PCODE5                  1230
#define IDC_EDT_RTV_ARRIVE              1230
#define IDC_EDT_USER_ID                 1231
#define IDC_EDT_DEST_POS                1231
#define IDC_BTN_SET3                    1231
#define IDC_EDT_USER_PW1                1232
#define IDC_EDT_DATE                    1232
#define IDC_BTN_SET7                    1232
#define IDC_BTN_SET2                    1232
#define IDC_EDT_USER_PW2                1233
#define IDC_EDT_TIME_START              1233
#define IDC_EDT_USER_NAME               1234
#define IDC_EDT_TIME_END                1234
#define IDC_CBX_LEVEL                   1235
#define IDC_EDT_WORKER1                 1235
#define IDC_EDT_BASKET1                 1236
#define IDC_EDT_WORKER2                 1236
#define IDC_EDT_BASKET2                 1237
#define IDC_CBX_JOB_PLAN                1237
#define IDC_EDT_BASKET3                 1238
#define IDC_STATIC_MESSAGE              1238
#define IDC_EDT_PINFO                   1238
#define IDC_EDT_BASKET4                 1239
#define IDC_EDT_USER_PW                 1239
#define IDC_EDT_BASKET_SEQ              1239
#define IDC_EDT_BASKET5                 1240
#define IDC_BTN_FIND                    1240
#define IDC_EDT_BASKET6                 1241
#define IDC_TAB                         1241
#define IDC_STATIC_ROOM                 1244
#define IDC_CHK_BATCH_FILTER            1245
#define IDC_CHK_CONNECT                 1248
#define IDC_CHK_RETRY                   1249
#define IDC_EDT_COMNAME                 1249
#define IDC_EDT_BAUD_RATE               1250
#define IDC_CHK_WRITE_LOG               1250
#define IDC_EDT_PARITY                  1251
#define IDC_EDT_BIT_PER_CHAR            1252
#define IDC_EDT_READ_TIMEOUT            1253
#define IDC_EDT_STOP_BITS               1254
#define IDC_BTN_IN_DOOR_OPEN            1254
#define IDC_BTN_OUT_DOOR_OPEN           1255
#define IDC_BTN_IO1                     1255
#define IDC_BTN_IO2                     1256
#define IDC_BTN_IO3                     1257
#define IDC_BTN_IO4                     1258
#define IDC_BTN_IO5                     1259
#define IDC_BTN_IO6                     1260
#define IDC_BTN_IO7                     1261
#define IDC_BTN_IO8                     1262
#define IDC_STATIC_IO1                  1263
#define IDC_STATIC_IO2                  1264
#define IDC_STATIC_IO3                  1265
#define IDC_STATIC_IO4                  1266
#define IDC_STATIC_IO5                  1267
#define IDC_STATIC_IO6                  1268
#define IDC_STATIC_IO7                  1269
#define IDC_STATIC_IO8                  1270
#define IDC_BTN2_IO1                    1271
#define IDC_BTN_IO9                     1271
#define IDC_BTN2_IO2                    1272
#define IDC_STATIC_IO9                  1272
#define IDC_BTN2_IO3                    1273
#define IDC_BTN2_IO4                    1274
#define IDC_BTN2_IO5                    1275
#define IDC_BTN2_IO6                    1276
#define IDC_BTN2_IO7                    1277
#define IDC_BTN2_IO8                    1278
#define IDC_STATIC2_IO1                 1279
#define IDC_STATIC2_IO2                 1280
#define IDC_STATIC2_IO3                 1281
#define IDC_STATIC2_IO4                 1282
#define IDC_STATIC2_IO5                 1283
#define IDC_STATIC2_IO6                 1284
#define IDC_STATIC2_IO7                 1285
#define IDC_STATIC2_IO8                 1286
#define IDC_BTN1_IO1                    1287
#define IDC_BTN1_IO2                    1288
#define IDC_BTN1_IO3                    1289
#define IDC_BTN1_IO4                    1290
#define IDC_BTN1_IO5                    1291
#define IDC_BTN1_IO6                    1292
#define IDC_BTN1_IO7                    1293
#define IDC_BTN1_IO8                    1294
#define IDC_STATIC1_IO1                 1295
#define IDC_STATIC1_IO2                 1296
#define IDC_STATIC1_IO3                 1297
#define IDC_STATIC1_IO4                 1298
#define IDC_STATIC1_IO5                 1299
#define IDC_STATIC1_IO6                 1300
#define IDC_STATIC1_IO7                 1301
#define IDC_STATIC1_IO8                 1302
#define IDC_EDT_DATE4                   1303
#define IDC_EDT_DATE5                   1304
#define IDC_EDT_DATE6                   1305
#define IDC_EDT_DATE3                   1306
#define IDC_EDT_DATE2                   1307
#define IDC_BTN_READ_DATA               1308
#define IDC_BTN_WRITE_DATA              1311
#define IDC_EDT_MESSAGE                 1312
#define IDC_BTN_COMMAND                 1313
#define IDC_BTN_REQUEST_RPOD            1314
#define IDC_BTN_REQUEST_PLT             1315
#define IDC_BTN_ERROR_RESET             1316
#define IDC_SCCTRL4                     1324
#define IDC_BUTTON2                     1325
#define IDC_BUTTON_REQUEST_AGV_STATUS   1325
#define IDC_BUTTON3                     1326
#define IDC_BTN_JOB_RESULT              1326
#define IDC_BUTTON_DOOR1_OPEN           1326
#define IDC_BUTTON4                     1327
#define IDC_BTN_JOB_RESULT2             1327
#define IDC_BUTTON_DOOR2_OPEN           1327
#define IDC_BUTTON5                     1328
#define IDC_BTN_JOB_TYPE                1328
#define IDC_BUTTON_DOOR1_CLOSE          1328
#define IDC_BUTTON6                     1329
#define IDC_BTN_JOB_RESULT3             1329
#define IDC_BUTTON_DOOR2_CLOSE          1329
#define IDC_BUTTON_DOOR1_OPEN_ACCEPT    1329
#define IDC_BUTTON7                     1330
#define IDC_BTN_DEST_POS                1330
#define IDC_BUTTON_DOOR1_REPORT         1330
#define IDC_BUTTON8                     1331
#define IDC_BTN_JOB_RESULT4             1331
#define IDC_BUTTON_DOOR2_REPORT         1331
#define IDC_BUTTON9                     1332
#define IDC_BTN_ERROR_STATUS            1332
#define IDC_BUTTON10                    1333
#define IDC_BTN_JOB_RESULT5             1333
#define IDC_BUTTON11                    1334
#define IDC_BTN_DEPART_TRACK            1334
#define IDC_BTN_START                   1334
#define IDC_BUTTON12                    1335
#define IDC_EDT_PLAN_CNT                1492
#define IDC_EDT_JOB_NUM                 1493
#define IDC_CHECK1                      1494
#define IDC_CHECK_PAIR                  1494
#define IDC_CHECK_CHANGE_PASS           1494
#define IDC_CHECK2                      1495
#define IDC_CHECK_AUTO                  1495
#define IDC_CHECK_2FORK                 1495
#define IDC_IPADDRESS1                  1496
#define IDC_IPADDRESS                   1496
#define IDC_CHECK_BIG                   1496
#define IDC_EDIT_JOB_ARRIVE_POS         1497
#define IDC_EDIT_JOB_DEST_STN           1497
#define IDC_TAB_AGV                     1501
#define IDC_BUTTON_REQUEST_RESET        1503
#define IDC_EDIT_PROD_LOAD              1504
#define IDC_EDIT_CMD_TYPE               1505
#define IDC_EDIT_CMD_TYPE2              1506
#define IDC_TAB_COMMAND                 1507
#define IDC_EDIT_DEPART_POS             1508
#define IDC_EDIT_ARRIVE_POS             1509
#define IDC_EDIT_SC_JOB_STATUS          1510
#define IDC_EDIT_BCR_TRACK              1511
#define IDC_EDIT_BCR_BARCODE            1512
#define IDC_BUTTON_READ_BARCODE         1513
#define IDC_BUTTON_RESET_ERROR          1514
#define IDC_EDIT_DEVICE                 1515
#define IDC_BUTTON_REQUEST_STORE        1516
#define IDC_EDIT_REQUEST_BARCODE        1517
#define IDC_EDIT_BCR_TIME               1518
#define IDC_EDIT_MESSAGE                1519
#define IDC_EDIT_LIFTER_MODE            1520
#define IDC_EDIT_REQUEST_STATUS         1520
#define IDC_EDIT_LIFTER_STATUS          1521
#define IDC_BUTTON_WRITE_DATA           1521
#define IDC_EDIT_LIFTER_WORK            1522
#define IDC_BUTTON_CLEAR_DATA           1522
#define IDC_EDIT_LIFTER_PRODLOAD        1523
#define IDC_BUTTON_WRITE_CRATE_STATUS   1523
#define IDC_EDIT_LIFTER_FLOOR           1524
#define IDC_BUTTON_WRITE_BIDP_ID        1524
#define IDC_BUTTON_SENSOR1              1525
#define IDC_BUTTON_SENSOR_PRODUCT1      1525
#define IDC_EDIT_GEN_CODE               1525
#define IDC_BUTTON_ARRIVE_REPORT        1525
#define IDC_BUTTON_SENSOR2              1526
#define IDC_BUTTON_STATUS_CV_CHECK_POS  1526
#define IDC_BUTTON_SENSOR3              1527
#define IDC_BUTTON_SENSOR_SC_INTERLOCK  1527
#define IDC_BUTTON_SENSOR4              1528
#define IDC_BUTTON_SENSOR_RTV_INTERLOCK 1528
#define IDC_BUTTON_SENSOR5              1529
#define IDC_BUTTON_SENSOR_LGV_INTERLOCK 1529
#define IDC_BUTTON_SENSOR6              1530
#define IDC_BUTTON_SENSOR_LIFTER_INTERLOCK 1530
#define IDC_BUTTON_STATUS11             1531
#define IDC_BUTTON_STATUS_STO_STATION   1531
#define IDC_BUTTON_DATA                 1532
#define IDC_BUTTON_STATUS12             1533
#define IDC_BUTTON_CHECK                1533
#define IDC_BUTTON_STATUS_RET_STATION   1533
#define IDC_BUTTON_STATUS13             1534
#define IDC_BUTTON_TEST                 1534
#define IDC_BUTTON_STATUS_SC_STO_HS     1534
#define IDC_BUTTON_STATUS14             1535
#define IDC_BUTTON_CLEAR                1535
#define IDC_BUTTON_STATUS_SC_RET_HS     1535
#define IDC_BUTTON_STATUS15             1536
#define IDC_BUTTON_ERROR                1536
#define IDC_EDIT_COMM_STATUS            1536
#define IDC_BUTTON_STATUS_RTV_DEPART_HS 1536
#define IDC_BUTTON_STATUS16             1537
#define IDC_BUTTON_STATUS_RTV_ARRIVE_HS 1537
#define IDC_BUTTON_STATUS17             1538
#define IDC_TAB_JOB_TYPE                1538
#define IDC_BUTTON_STATUS_LGV_DEPART_HS 1538
#define IDC_BUTTON_STATUS18             1539
#define IDC_BUTTON_STATUS_LGV_ARRIVE_HS 1539
#define IDC_BUTTON_STATUS19             1540
#define IDC_BUTTON_READ_DATA            1540
#define IDC_BUTTON_STATUS_LIFTER_DEPART_HS 1540
#define IDC_BUTTON_STATUS20             1541
#define IDC_EDIT_RFID_TRACK             1541
#define IDC_BUTTON_STATUS_LIFTER_ARRIVE_HS 1541
#define IDC_BUTTON_STATUS21             1542
#define IDC_BUTTON_STATUS_LGV_IN_REQUEST 1542
#define IDC_BUTTON_STATUS22             1543
#define IDC_EDIT_RFID_TIME              1543
#define IDC_BUTTON_STATUS_LGV_OUT_REQUEST 1543
#define IDC_EDIT_TAG_CRATE_STATUS       1544
#define IDC_EDIT_TAG_BIDP_ID            1545
#define IDC_EDIT_JOB_LUGG_NUM           1546
#define IDC_EDIT_JOB_PROD_INFO          1547
#define IDC_EDIT_DEST_TRACK             1548
#define IDC_EDIT_JOB_PROD_INFO2         1548
#define IDC_EDIT_JOB_PROD_INFO3         1549
#define IDC_STATIC_LOGO                 1549
#define IDC_EDIT_SIZE_CODE              1549
#define IDC_EDIT_JOB_PROD_INFO4         1550
#define IDC_EDIT_JOB_PROD_INFO5         1551
#define IDC_LAYOUT_TAB                  1552
#define IDC_EDIT_JOB_BIDP_ID            1553
#define IDC_EDIT_BANK                   1553
#define IDC_EDIT_BAY                    1554
#define IDC_EDIT_LEVEL                  1555
#define IDC_BTN_RACK_WRITE              1556
#define IDC_LIST_RACK                   1557
#define IDC_EDIT_BANK_CNT               1558
#define IDC_STATIC_RACK_CNT             1558
#define IDC_EDIT_BAY_CNT                1559
#define IDC_EDIT_LEVEL_CNT              1560
#define IDC_STATIC_PAIR_DESC            1560
#define IDC_RADIO_BELT_LMOVE            1561
#define IDC_RADIO_BELT_RMOVE            1562
#define IDC_STATIC_BMP                  1562
#define IDC_STATIC_ETC                  1564
#define IDC_BTN_DISABLE_RACK            1565
#define IDC_CMB_PLT                     1566
#define IDC_STATIC_GROUP                1567
#define IDC_CHECK_LAMP                  1568
#define IDC_STATIC_NEW_PASSWORD         1569
#define IDC_STATIC_PASSWORD_CONFIRM     1570
#define IDC_VIEW_LAMP                   1571
#define IDC_STATIC_LAMP                 1572
#define IDC_VIEW_PRODUCT_INFO           1572
#define IDC_STATIC_PRODUCT_INFO         1573
#define IDC_LOG                         1573
#define IDC_NOT_CHECK_RET_HS            1574
#define IDC_NOT_CHECK_RET_HS_SC1        1575
#define IDC_NOT_CHECK_RET_HS_SC2        1576
#define IDC_NOT_CHECK_RET_HS_SC3        1577
#define IDC_NOT_CHECK_RET_HS_SC4        1578
#define IDC_NOT_CHECK_RET_HS_SC5        1579
#define IDC_NOT_CHECK_RET_HS_SC6        1580
#define IDC_CHECK_NO_BACKUP_NETWORK     1581
#define IDC_STATIC_QNT                  1582
#define IDC_STATIC_QTY_GROUP            1583
#define IDC_CHK_TEST_START1             1585
#define IDC_STC_WORK_LUGG1              1586
#define IDC_STC_DUAL_STO_LOC            1587
#define IDC_STC_WORK_LUGG2              1588
#define IDC_CHK_TEST_START2             1589
#define IDC_LOGIC_GROUP                 1590
#define IDC_BTN_END                     1591
#define IDC_LIST_HOST_CL                1593
#define IDC_LIST_HOST_SV                1594
#define IDC_LIST_ALL_JOB                1595
#define IDC_COMBO_RGV_START             1601
#define IDC_COMBO_DEPART_POS            1601
#define IDC_COMBO_RGV_DEST              1602
#define IDC_COMBO_ARRIVE_POS            1602
#define IDC_EDIT_MC_ADDR                1605
#define IDC_EDIT_MC_PORT                1606
#define IDC_EDIT_MC_TTL                 1607
#define IDC_CHECK_MC_LOOP_BACK          1608
#define IDC_EDIT_MC_MACHINE_NAME        1609
#define IDC_EDIT_MC_LOCAL_IP            1610
#define IDC_EDIT_MC_LOCAL_PORT          1611
#define IDC_EDIT_ECSSV_PORT             1612
#define IDC_LIST_CLIENT                 1613
#define IDC_EDIT_MC_SEND_BUFFER         1616
#define IDC_EDIT_MC_RECV_BUFFER         1617
#define IDC_BUTTON_DISPLAY              1644
#define IDC_EDIT_JOB_PATH               1646
#define IDC_BUTTON_JOB_PATH             1647
#define IDC_EDIT_STC_PATH               1648
#define IDC_BUTTON_STC_PATH             1649
#define IDC_EDIT_LOG_PATH               1650
#define IDC_BUTTON_LOG_PATH             1651
#define IDC_EDIT_INFO_PATH              1652
#define IDC_BUTTON_INFO_PATH            1653
#define IDC_EDIT_JOB_FILE               1654
#define IDC_EDIT_STC_FILE               1655
#define IDC_EDIT_INFO_PATH2             1655
#define IDC_EDIT_LOG_FILE               1656
#define IDC_EDIT_INFO_FILE              1657
#define IDC_EDIT_INFO_FILE2             1658
#define IDC_BUTTON_INFO_PATH2           1659
#define IDC_BUTTON_CV1                  1661
#define IDC_BTN_AUTO_STO                1661
#define IDC_BUTTON_CV2                  1662
#define IDC_BUTTON_CV3                  1663
#define IDC_BUTTON_RTV1                 1664
#define IDC_BUTTON_RTV2                 1665
#define IDC_BUTTON_RTV3                 1666
#define IDC_BUTTON_LOADER1              1666
#define IDC_BUTTON_LOADER2              1667
#define IDC_BTN_AUTO_RET                1667
#define IDC_BUTTON_UNLOADER1            1668
#define IDC_BTN_AUTO_RTR                1668
#define IDC_STATIC_LUGG_NUM             1669
#define IDC_BUTTON_UNLOADER2            1669
#define IDC_BTN_AUTO_WTW                1669
#define IDC_STATIC_JOB_TYPE             1670
#define IDC_GROUP                       1670
#define IDC_STATIC_START_POS            1671
#define IDC_STATIC_DEST_POS             1672
#define IDC_STATIC_LUGG_NUM2            1673
#define IDC_BTN_MANUAL                  1674
#define IDC_STATIC_START_POS2           1674
#define IDC_STATIC_LOCATION             1675
#define IDC_STATIC_DEST_POS2            1675
#define IDC_STATIC_PRODUCT              1676
#define IDC_BTN_SEMI_STO                1676
#define IDC_STATIC_JOB_TYPE2            1676
#define IDC_STATIC_JOB_PROGRESS         1677
#define IDC_BTN_SEMI_RET                1677
#define IDC_STATIC_PRODUCT2             1678
#define IDC_BTN_SEMI_RTR                1678
#define IDC_STATIC_PRODUCT3             1679
#define IDC_STATIC_INTERNAL_LUGG_NUM    1679
#define IDC_BTN_SEMI_WTW                1679
#define IDC_STATIC_PRODUCT4             1680
#define IDC_BTN_SEMI_MOVE               1680
#define IDC_STATIC_INTERNAL_LUGG_NUM2   1680
#define IDC_STATIC_PRODUCT5             1681
#define IDC_BTN_ALARM                   1681
#define IDC_STATIC_STN_MODE             1682
#define IDC_BTN_ERROR                   1682
#define IDC_BTN_SUSPEND                 1683
#define IDC_BTN_AUTO_MOVE               1684
#define IDC_BTN_TRACK_STO_ST            1685
#define IDC_BTN_TRACK_RET_ST            1686
#define IDC_BTN_TRACK_ARV_ST            1687
#define IDC_BTN_TRACK_DEPART_HS         1688
#define IDC_BTN_TRACK_ARRIVE_HS         1689
#define IDC_BTN_DISCONNECT              1690
#define IDC_BTN_SC_STO_ERROR            1691
#define IDC_EDIT_RGV_ACTIVE             1693
#define IDC_RADIO_STO_COMPLETE          1693
#define IDC_BTN_SC_RET_ERROR            1693
#define IDC_RADIO_RET_COMPLETE          1694
#define IDC_BUTTON_SIDE_LOGO            1719
#define IDC_EDIT_SIDE_LOGO              1720
#define IDC_EDIT_MENU_LOGO              1721
#define IDC_BUTTON_MENU_LOGO            1722
#define IDC_BUTTON_SORT                 1764
#define IDC_STATIC_TOP                  1765
#define IDC_STATIC_BOTTOM               1766
#define IDC_BUTTON_STO_REQUEST          1771
#define IDC_EDIT_MON_PORT               1773
#define IDC_EDIT_PORT_MON               1773
#define IDC_EDIT_UNITID                 1774
#define IDC_STATIC_FORK_TWO             1777
#define IDC_STATIC_FORK_STATUS          1778
#define IDC_COMBO_PRODGEN               1791
#define IDC_CHECK_URGENT                1795
#define IDC_EDIT_SEQ                    1795
#define IDC_STATIC_EDGE                 1802
#define IDC_LIST_OUTLOOK                1805
#define IDC_STATIC_RIGHT                1809
#define IDC_LIST_WARNING                1839
#define IDC_STATIC_TIP                  1840
#define IDC_STATIC_PANE                 1841
#define IDC_BUTTON_NEXT                 1844
#define IDC_BUTTON_PREV                 1845
#define IDC_BUTTON_FIRST                1847
#define IDC_BUTTON_LAST                 1848
#define IDD_BUTTON_RESET_REPORT         1857
#define IDC_BTN_QUERY                   1875
#define IDC_BTN_INSERT                  1876
#define IDC_USER_ID                     1895
#define IDC_USER_NAME                   1896
#define IDC_PASSWORD                    1897
#define IDC_PWD_CONFIRM                 1898
#define IDC_BUTTON_MANUAL               2123
#define IDC_BUTTON_CYCLE_STEP_ORDER     2123
#define IDC_BUTTON_IO                   2124
#define IDC_EDIT_PASSWORD_ORGIN         2125
#define IDC_EDIT_PASSWORD_CHANGED       2126
#define IDC_EDIT_PASSWORD_CONFIRM       2127
#define IDC_FORK1                       2548
#define IDC_FORK2                       2549
#define IDC_FORK12                      2550
#define IDC_EDIT_DEPART2                2722
#define IDC_EDIT_ARRIVE2                2724
#define IDD_PASSWORD                    3015
#define IDD_PASSWORD_CHANGE             3016
#define ID_LOG_ALL                      3021
#define ID_LOG_ERROR                    3022
#define ID_LOG_MODE                     3023
#define ID_VIEW_TOOLBAR_COM             3024
#define IDD_SC_CHECK_DELETION           3045
#define IDD_CONFIG_SUB3_PAGE            3046
#define IDD_SC_HALF_CYCLE_CTRL          3047
#define IDD_SC_HALF_PAIR_CTRL           3048
#define IDD_LGVC_CTRL                   3049
#define IDD_LGV_CTRL1                   3050
#define ID_USER_LOGO                    9997
#define ID_MAKER_LOGO                   9998
#define ID_COM_HOST_SERVER              10001
#define ID_COM_HOST_CLIENT              10002
#define ID_COM_CV01                     11001
#define ID_COM_CV02                     11002
#define ID_COM_CV03                     11003
#define ID_COM_CV04                     11004
#define ID_COM_CV05                     11005
#define ID_COM_CV06                     11006
#define ID_COM_CV07                     11007
#define ID_COM_CV08                     11008
#define ID_COM_CV09                     11009
#define ID_COM_CV10                     11010
#define ID_COM_CV11                     11011
#define ID_COM_CV12                     11012
#define ID_COM_SC1_W1                   12001
#define ID_COM_SC2_W1                   12002
#define ID_COM_SC3_W1                   12003
#define ID_COM_SC4_W1                   12004
#define ID_COM_SC5_W1                   12005
#define ID_COM_SC6_W1                   12006
#define ID_COM_RTV1                     13101
#define ID_COM_RTV2                     13102
#define ID_COM_BCR1                     17001
#define ID_LOG_FILE                     20001
#define ID_LOG_EXIT                     20002
#define ID_LOG_SAVEAS                   20003
#define ID_LOG_PRINT                    20004
#define ID_REFRESH_LOG                  20005
#define IDC_GMSBTNCTRL1                 30001
#define IDC_GMSBTNCTRL2                 30002
#define IDC_GMSBTNCTRL3                 30003
#define IDC_GMSBTNCTRL4                 30004
#define IDC_GMSBTNCTRL5                 30005
#define IDC_GMSBTNCTRL6                 30006
#define ID_JOB_MANAGER                  32804
#define ID_SYSTEM_RTV                   32805
#define ID_VIEW_LAYOUT_INFO             32833
#define ID_SYSTEM_CONFIG1               32834
#define ID_SYSTEM_CONFIG2               32835
#define ID_SYSTEM_CONFIG3               32836
#define ID_WARNING                      32838
#define ID_JOB_OFFLINE                  32842
#define ID_BUTTON32859                  32859
#define ID_BUTTON32860                  32860
#define ID_BUTTON32863                  32863
#define ID_BUTTON32864                  32864
#define ID_BUTTON32865                  32865
#define ID_BUTTON32866                  32866
#define ID_BUTTON32867                  32867
#define ID_BUTTON32868                  32868
#define ID_JOB_TEST                     32881
#define ID_SET_ALL_SUSPEND              32884
#define ID_UNSET_ALL_SUSPEND            32885
#define ID_SYSTEM_CONFIG4               32887
#define ID_RACK_CONFIG                  32887
#define ID_SYS_USER_MANAGER             32913
#define ID_MENUITEM32914                32914
#define ID_INPUT_MESSAGE                32916
#define ID_JOB_OFFLINE2                 32917
#define ID_JOB_OFFLINE1                 32918

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        374
#define _APS_NEXT_COMMAND_VALUE         32919
#define _APS_NEXT_CONTROL_VALUE         1596
#define _APS_NEXT_SYMED_VALUE           111
#endif
#endif
