-- ============================================================
-- IO_TASK WCS  MS-SQL 스키마 (PostgreSQL LGLS_TEST 기준 자동 변환)
-- 생성: 2026-07-08  /  재고관리(CELL_MST/CELL_DTL/HOST_EMPTY_PLT) 제외
-- 대상: 반송 스케줄러 + 통신 Task(C/V, S/C, RGV, BCR) 관련 테이블
-- ============================================================
-- USE [LglsMCS];
-- GO

IF OBJECT_ID('dbo.JOB_MST','U') IS NOT NULL DROP TABLE dbo.JOB_MST;
GO
CREATE TABLE dbo.JOB_MST (
    [WH_TYP] VARCHAR(4) NULL,
    [LUGG_NO] VARCHAR(4) NULL,
    [START_POS] VARCHAR(5) NULL,
    [START_LOCATION] VARCHAR(9) NULL,
    [DEST_POS] VARCHAR(5) NULL,
    [DEST_LOCATION] VARCHAR(9) NULL,
    [TURN] VARCHAR(2) NULL,
    [PRODUCT_ID] VARCHAR(300) NULL,
    [PRODUCT_SIZE] VARCHAR(10) NULL,
    [JOB_TYP] VARCHAR(4) NULL,
    [BCR_TOP] VARCHAR(50) NULL,
    [BCR_BOTTOM] VARCHAR(50) NULL,
    [MES_WRITE_YN] VARCHAR(1) NULL,
    [JOB_KIND] VARCHAR(5) NULL,
    [JOB_STATUS] VARCHAR(5) NULL,
    [JOB_PRIORITY] VARCHAR(4) NULL,
    [MES_ERROR_CD] VARCHAR(4) NULL,
    [CMD_STA] VARCHAR(5) NULL,
    [OD_LAST_PAGE] VARCHAR(20) NULL,
    [OD_LAST_USER] VARCHAR(20) NULL,
    [JOB_START_DT] DATETIME NULL,
    [UPD_DT] DATETIME NULL,
    [UPD_USER_ID] VARCHAR(20) NULL,
    [INS_DT] DATETIME NULL,
    [INS_USER_ID] VARCHAR(20) NULL,
    [REMARKS] VARCHAR(50) NULL,
    [TRAY_TYP] VARCHAR(10) NULL,
    [TRAY_LEV] VARCHAR(10) NULL,
    [HS_TRACK_NO] VARCHAR(5) NULL,
    [SC_NO] VARCHAR(5) NULL,
    [DURATION_TIME] VARCHAR(20) NULL,
    [SYSTEM_BYTE] VARCHAR(30) NULL,
    [S6F12_RESPONSE] VARCHAR(1) NULL,
    [S6F11_YON] VARCHAR(1) NULL,
    [CEID_NAME] VARCHAR(20) NULL,
    [DEL_YN] VARCHAR(1) NULL,
    [FK_NO] VARCHAR(1) NULL,
    [AGING_TIME] DATETIME NULL,
    [PAIR_LUGG_NO] VARCHAR(10) NULL,
    [LOT_NO] VARCHAR(50) NULL,
    [WC_STEP] VARCHAR(5) NULL,
    [CMP_STEP] VARCHAR(5) NULL
);
GO

IF OBJECT_ID('dbo.JOB_MST_HIS','U') IS NOT NULL DROP TABLE dbo.JOB_MST_HIS;
GO
CREATE TABLE dbo.JOB_MST_HIS (
    [INS_DATE] VARCHAR(12) NULL,
    [INS_TIME] VARCHAR(6) NULL,
    [WH_TYP] VARCHAR(4) NULL,
    [LUGG_NO] VARCHAR(4) NULL,
    [START_POS] VARCHAR(5) NULL,
    [START_LOCATION] VARCHAR(9) NULL,
    [DEST_POS] VARCHAR(5) NULL,
    [DEST_LOCATION] VARCHAR(9) NULL,
    [TURN] VARCHAR(2) NULL,
    [PRODUCT_ID] VARCHAR(300) NULL,
    [PRODUCT_SIZE] VARCHAR(10) NULL,
    [JOB_TYP] VARCHAR(4) NULL,
    [BCR_TOP] VARCHAR(50) NULL,
    [BCR_BOTTOM] VARCHAR(50) NULL,
    [MES_WRITE_YN] VARCHAR(1) NULL,
    [CMD_STA] VARCHAR(5) NULL,
    [JOB_KIND] VARCHAR(5) NULL,
    [JOB_STATUS] VARCHAR(5) NULL,
    [JOB_PRIORITY] VARCHAR(4) NULL,
    [MES_ERROR_CD] VARCHAR(4) NULL,
    [OD_LAST_PAGE] VARCHAR(20) NULL,
    [OD_LAST_USER] VARCHAR(20) NULL,
    [JOB_START_DT] DATETIME NULL,
    [UPD_DT] DATETIME NULL,
    [UPD_USER_ID] VARCHAR(20) NULL,
    [INS_DT] DATETIME NULL,
    [INS_USER_ID] VARCHAR(20) NULL,
    [REMARKS] VARCHAR(50) NULL,
    [TRAY_TYP] VARCHAR(10) NULL,
    [TRAY_LEV] VARCHAR(10) NULL,
    [HS_TRACK_NO] VARCHAR(5) NULL,
    [SC_NO] VARCHAR(5) NULL,
    [DURATION_TIME] VARCHAR(10) NULL,
    [SYSTEM_BYTE] VARCHAR(30) NULL,
    [S6F12_RESPONSE] VARCHAR(1) NULL,
    [S6F11_YON] VARCHAR(1) NULL,
    [CEID_NAME] VARCHAR(20) NULL,
    [DEL_YN] VARCHAR(1) NULL,
    [FK_NO] VARCHAR(1) NULL,
    [AGING_TIME] DATETIME NULL,
    [PAIR_LUGG_NO] VARCHAR(10) NULL,
    [LOT_NO] VARCHAR(30) NULL,
    [CMP_STEP] VARCHAR(5) NULL
);
GO

IF OBJECT_ID('dbo.CV_DATA','U') IS NOT NULL DROP TABLE dbo.CV_DATA;
GO
CREATE TABLE dbo.CV_DATA (
    [WH_TYP] VARCHAR(4) NULL,
    [PLC_NO] VARCHAR(5) NULL,
    [TRACK_NO] VARCHAR(5) NULL,
    [MC_NO] VARCHAR(5) NULL,
    [MC_NO_NM] VARCHAR(100) NULL,
    [LUGG_NO_RD] VARCHAR(5) NULL,
    [LUGG_NO_OD] VARCHAR(5) NULL,
    [DEST_POS_RD] VARCHAR(5) NULL,
    [DEST_POS_OD] VARCHAR(5) NULL,
    [JOB_TYP_RD] VARCHAR(5) NULL,
    [JOB_TYP_OD] VARCHAR(5) NULL,
    [TR_PAUSE_RD] VARCHAR(5) NULL,
    [TR_PAUSE_OD] VARCHAR(5) NULL,
    [COMMING_RD] VARCHAR(5) NULL,
    [COMMING_OD] VARCHAR(5) NULL,
    [ERROR_CODE] VARCHAR(5) NULL,
    [AUTO_MODE_RD] VARCHAR(5) NULL,
    [STO_READY_RD] VARCHAR(5) NULL,
    [RET_READY_RD] VARCHAR(5) NULL,
    [STOHS_READY_RD] VARCHAR(5) NULL,
    [RETHS_READY_RD] VARCHAR(5) NULL,
    [RTV_DEPARTHS_READY_RD] VARCHAR(5) NULL,
    [RTV_ARRIVEHS_READY_RD] VARCHAR(5) NULL,
    [SENSOR0_DATA_RD] VARCHAR(5) NULL,
    [SENSOR1_DATA_RD] VARCHAR(5) NULL,
    [SENSOR2_DATA_RD] VARCHAR(5) NULL,
    [DELETE_TRACK_RD] VARCHAR(5) NULL,
    [RTV_LOCK_SENSOR] VARCHAR(5) NULL,
    [BARCODE] VARCHAR(30) NULL,
    [ERR_RQ_RD] VARCHAR(5) NULL,
    [ERR_RQ_OD] VARCHAR(5) NULL,
    [OD_RQ_YN] VARCHAR(5) NULL,
    [OD_RQ_FLAG] VARCHAR(1) NULL,
    [CMD_RQ_ID] VARCHAR(20) NULL,
    [CMD_RQ_YN] VARCHAR(1) NULL,
    [HOST_SEND_YN] VARCHAR(1) NULL,
    [HOST_ERR_SEND_YN] VARCHAR(1) NULL,
    [USE_YN] VARCHAR(1) NULL,
    [READ_UPD_DT] DATETIME NULL,
    [WRITE_UPD_DT] DATETIME NULL,
    [STN_KIND] VARCHAR(10) NULL,
    [OD_USER_ID] VARCHAR(20) NULL,
    [OD_UPD_DT] DATETIME NULL,
    [COMMING_DEST_TR] VARCHAR(255) NULL,
    [COMMING_CHECK_TR1] VARCHAR(255) NULL,
    [COMMING_CHECK_TR2] VARCHAR(255) NULL,
    [COMMING_CHECK_TR3] VARCHAR(255) NULL,
    [COMMING_CHECK_TR4] VARCHAR(255) NULL,
    [DOOR_STATUS_RD] VARCHAR(255) NULL,
    [D5N_4_RD] VARCHAR(255) NULL,
    [PULP_SENSOR_RD] VARCHAR(255) NULL,
    [CV_CHECK_POS_RD] VARCHAR(255) NULL,
    [D5N_1_RD] VARCHAR(255) NULL,
    [EMERGENCY_RD] VARCHAR(255) NULL,
    [REMOTE_CONTROL] VARCHAR(255) NULL,
    [ROLL_MODE] VARCHAR(255) NULL,
    [STOCK_MODE] VARCHAR(255) NULL,
    [A_TURN_YN] VARCHAR(255) NULL,
    [B_TURN_YN] VARCHAR(255) NULL,
    [WAIT_SC_RET_JOB_RD] VARCHAR(255) NULL,
    [SC_LOCK_SENSOR] VARCHAR(255) NULL,
    [DRIV_PAPER_POS] VARCHAR(255) NULL,
    [ELEV_ASC_ERR] VARCHAR(255) NULL,
    [ELEV_DESC_ERR] VARCHAR(255) NULL,
    [CLAMP_FORWARD_ERR] VARCHAR(255) NULL,
    [CLAMP_BACKWARD_ERR] VARCHAR(255) NULL,
    [DRIV_FORWARD_ERR] VARCHAR(255) NULL,
    [DRIV_BACKWARD_ERR] VARCHAR(255) NULL,
    [PAPER_BLOCK_SENSOR1] VARCHAR(255) NULL,
    [PAPER_BLOCK_SENSOR2] VARCHAR(255) NULL,
    [PAPER_BLOCK_SENSOR3] VARCHAR(255) NULL,
    [PAPER_BLOCK_SENSOR4] VARCHAR(255) NULL,
    [PAPER_FULL_SENSOR] VARCHAR(255) NULL,
    [DRIV_FORWARD_POS] VARCHAR(255) NULL,
    [DRIV_BACKWARD_POS] VARCHAR(255) NULL,
    [CRUSH_PAPER_SENSOR] VARCHAR(255) NULL,
    [CLAMP_FORWARD_SENSOR] VARCHAR(255) NULL,
    [CLAMP_BACKWARD_SENSOR] VARCHAR(255) NULL,
    [REV_ELEV_POS_DATA_ASC] VARCHAR(255) NULL,
    [REV_ELEV_POS_DATA_1] VARCHAR(255) NULL,
    [REV_ELEV_POS_DATA_2] VARCHAR(255) NULL,
    [REV_DRIV_POS_DATA_PICKUP] VARCHAR(255) NULL,
    [REV_DRIV_POS_DATA_REVERSE] VARCHAR(255) NULL,
    [REV_SENSOR_DATA_HEIGHT] VARCHAR(255) NULL,
    [ROLL_ELEV_POS_DATA_PICKUP] VARCHAR(255) NULL,
    [ROLL_ELEV_POS_DATA_ROLLING] VARCHAR(255) NULL,
    [ROLL_CLAMP_POS_DATA_BACKWARD] VARCHAR(255) NULL,
    [ROLL_CLAMP_POS_DATA_FORWARD] VARCHAR(255) NULL,
    [ROLL_SENSOR_DATA_HEIGHT] VARCHAR(255) NULL,
    [TRACKING_WRITE_YN] VARCHAR(255) NULL
);
GO

IF OBJECT_ID('dbo.SC_DATA','U') IS NOT NULL DROP TABLE dbo.SC_DATA;
GO
CREATE TABLE dbo.SC_DATA (
    [WH_TYP] VARCHAR(4) NULL,
    [PLC_NO] VARCHAR(5) NULL,
    [SC_NO] VARCHAR(5) NULL,
    [SC_GRP_NO] VARCHAR(5) NULL,
    [MC_NO] VARCHAR(5) NULL,
    [MC_NO_NM] VARCHAR(100) NULL,
    [AUTO_MODE_RD] VARCHAR(4) NULL,
    [UCSTATUS_RD] VARCHAR(4) NULL,
    [ONLINE_MODE_RD] VARCHAR(1) NULL,
    [ACTIVE_MODE_RD] VARCHAR(4) NULL,
    [SENSOR_FK_RD] VARCHAR(1) NULL,
    [POS_H_RD] VARCHAR(5) NULL,
    [POS_V_RD] VARCHAR(5) NULL,
    [ERR_CODE_RD] VARCHAR(4) NULL,
    [COMPLETE_RD] VARCHAR(4) NULL,
    [JOB_TYP_RD] VARCHAR(4) NULL,
    [JOB_TYP_OD] VARCHAR(4) NULL,
    [LUGG_NO_FK1_RD] VARCHAR(4) NULL,
    [LUGG_NO_FK1_OD] VARCHAR(4) NULL,
    [ITN_LUGG_FK1] VARCHAR(5) NULL,
    [START_BANK_FK1_RD] VARCHAR(3) NULL,
    [START_BANK_FK1_OD] VARCHAR(3) NULL,
    [START_BAY_FK1_RD] VARCHAR(3) NULL,
    [START_BAY_FK1_OD] VARCHAR(3) NULL,
    [START_LEVEL_FK1_RD] VARCHAR(3) NULL,
    [START_LEVEL_FK1_OD] VARCHAR(3) NULL,
    [START_HSPOS_FK1_RD] VARCHAR(4) NULL,
    [START_HSPOS_FK1_OD] VARCHAR(4) NULL,
    [DEST_BANK_FK1_RD] VARCHAR(3) NULL,
    [DEST_BANK_FK1_OD] VARCHAR(3) NULL,
    [DEST_BAY_FK1_RD] VARCHAR(3) NULL,
    [DEST_BAY_FK1_OD] VARCHAR(3) NULL,
    [DEST_LEVEL_FK1_RD] VARCHAR(3) NULL,
    [DEST_LEVEL_FK1_OD] VARCHAR(3) NULL,
    [DEST_HSPOS_FK1_RD] VARCHAR(4) NULL,
    [DEST_HSPOS_FK1_OD] VARCHAR(4) NULL,
    [LUGG_NO_FK2_RD] VARCHAR(4) NULL,
    [LUGG_NO_FK2_OD] VARCHAR(4) NULL,
    [ITN_LUGG_FK2] VARCHAR(5) NULL,
    [START_BANK_FK2_RD] VARCHAR(3) NULL,
    [START_BANK_FK2_OD] VARCHAR(3) NULL,
    [START_BAY_FK2_RD] VARCHAR(3) NULL,
    [START_BAY_FK2_OD] VARCHAR(3) NULL,
    [START_LEVEL_FK2_RD] VARCHAR(3) NULL,
    [START_LEVEL_FK2_OD] VARCHAR(3) NULL,
    [START_HSPOS_FK2_RD] VARCHAR(4) NULL,
    [START_HSPOS_FK2_OD] VARCHAR(4) NULL,
    [DEST_BANK_FK2_RD] VARCHAR(3) NULL,
    [DEST_BANK_FK2_OD] VARCHAR(3) NULL,
    [DEST_BAY_FK2_RD] VARCHAR(3) NULL,
    [DEST_BAY_FK2_OD] VARCHAR(3) NULL,
    [DEST_LEVEL_FK2_RD] VARCHAR(3) NULL,
    [DEST_LEVEL_FK2_OD] VARCHAR(3) NULL,
    [DEST_HSPOS_FK2_RD] VARCHAR(4) NULL,
    [DEST_HSPOS_FK2_OD] VARCHAR(4) NULL,
    [ERR_STA_FK1_RD] VARCHAR(4) NULL,
    [ERR_STA_FK2_RD] VARCHAR(4) NULL,
    [FORKPOS_FK1_RD] VARCHAR(4) NULL,
    [FORKPOS_FK2_RD] VARCHAR(4) NULL,
    [USE_FK_RD] VARCHAR(4) NULL,
    [USE_FK_OD] VARCHAR(4) NULL,
    [STOCK_MODE] VARCHAR(4) NULL,
    [OD_RQ_YN] VARCHAR(1) NULL,
    [OD_RQ_FLAG] VARCHAR(1) NULL,
    [CMD_RQ_ID] VARCHAR(10) NULL,
    [CMD_RQ_YN] VARCHAR(1) NULL,
    [HOST_SEND_YN] VARCHAR(8) NULL,
    [HOST_ERR_SEND_YN] VARCHAR(8) NULL,
    [SUSPEND] VARCHAR(2) NULL,
    [READ_UPD_DT] DATETIME NULL,
    [WRITE_UPD_DT] DATETIME NULL,
    [OD_USER_ID] VARCHAR(20) NULL,
    [OD_UPD_DT] DATETIME NULL,
    [WRITE_CONTINUE_OD] VARCHAR(4) NULL,
    [WRITE_FLAG_OD] VARCHAR(4) NULL,
    [USER_COMMAND_OD] VARCHAR(4) NULL,
    [CV_WORKBENCH_RD] VARCHAR(4) NULL,
    [CV_WORKBENCH_SUB_RD] VARCHAR(4) NULL,
    [SC_TYP] VARCHAR(20) NULL,
    [PLT_INFO_RD] VARCHAR(1) NULL,
    [SC_VIEW_NM] VARCHAR(5) NULL,
    [CMD_RQ_PARM] VARCHAR(10) NULL,
    [SC_FIRE_OD] VARCHAR(10) NULL,
    [POOL_POSITION_RD] VARCHAR(5) NULL,
    [POOL_LIMIT_RD] VARCHAR(5) NULL,
    [POOL_WATER_LEVEL] VARCHAR(5) NULL,
    [SC_PLT_JOB_TYP_RD] VARCHAR(1) NULL,
    [SC_PLT_JOB_TYP_OD] VARCHAR(1) NULL
);
GO

IF OBJECT_ID('dbo.RTV_DATA','U') IS NOT NULL DROP TABLE dbo.RTV_DATA;
GO
CREATE TABLE dbo.RTV_DATA (
    [WH_TYP] VARCHAR(4) NULL,
    [PLC_NO] VARCHAR(5) NULL,
    [RTV_NO] VARCHAR(5) NULL,
    [AUTO_MODE_RD] VARCHAR(4) NULL,
    [WAITING_ORDER_RD] VARCHAR(255) NULL,
    [SENSOR_RTV_RD] VARCHAR(255) NULL,
    [ERR_CODE_RD] VARCHAR(255) NULL,
    [POS_H_RD] VARCHAR(255) NULL,
    [SPEED_RD] VARCHAR(255) NULL,
    [FD_OVERTIME_RD] VARCHAR(255) NULL,
    [SENSOR_FK1_RD] VARCHAR(255) NULL,
    [SENSOR_FK2_RD] VARCHAR(255) NULL,
    [READ_UPD_DT] DATETIME NULL,
    [CMD_RQ_YN] VARCHAR(255) NULL,
    [CMD_RQ_ID] VARCHAR(255) NULL,
    [OD_RQ_YN] VARCHAR(255) NULL,
    [RTV_PASSCV_OD] VARCHAR(255) NULL,
    [RTV_DEST_OD] VARCHAR(255) NULL,
    [WRITE_UPD_DT] DATETIME NULL,
    [LUGG_OD] VARCHAR(255) NULL,
    [STEP] VARCHAR(255) NULL,
    [JOB_TYP_OD] VARCHAR(255) NULL,
    [DEPART_TRACK] VARCHAR(255) NULL,
    [ARRIVE_TRACK] VARCHAR(255) NULL,
    [SUSPEND] VARCHAR(255) NULL,
    [OD_USER_ID] VARCHAR(255) NULL,
    [IS_ERROR_RD] VARCHAR(255) NULL
);
GO

IF OBJECT_ID('dbo.BCR_MST','U') IS NOT NULL DROP TABLE dbo.BCR_MST;
GO
CREATE TABLE dbo.BCR_MST (
    [WH_TYP] VARCHAR(4) NULL,
    [BCR_NO] VARCHAR(4) NULL,
    [BCR_MC_NO] VARCHAR(5) NULL,
    [UPD_DT] DATETIME NULL,
    [UPD_USER_ID] VARCHAR(20) NULL,
    [USE_YN] VARCHAR(1) NULL,
    [BCR_STA] VARCHAR(1) NULL,
    [BCR_LEV] VARCHAR(4) NULL,
    [NOREAD_CNT] INT NULL,
    [CMD_RQ_ID] VARCHAR(8) NULL,
    [CMD_RQ_YN] VARCHAR(1) NULL,
    [CV_LEV_MAX] INT NULL,
    [SUSPEND] VARCHAR(2) NULL,
    [BCR_UP_MC_NO] VARCHAR(5) NULL
);
GO

IF OBJECT_ID('dbo.BCR_DATA','U') IS NOT NULL DROP TABLE dbo.BCR_DATA;
GO
CREATE TABLE dbo.BCR_DATA (
    [WH_TYP] VARCHAR(4) NULL,
    [PLC_NO] VARCHAR(4) NULL,
    [BCR_NO] VARCHAR(4) NULL,
    [BCR_MC_NO] VARCHAR(5) NULL,
    [BCR_STA] VARCHAR(5) NULL,
    [BCR_RCV_VAL] VARCHAR(60) NULL,
    [CMD_RQ_ID] VARCHAR(5) NULL,
    [CMD_RQ_YN] VARCHAR(2) NULL,
    [USE_YN] VARCHAR(2) NULL,
    [UPD_DT] DATETIME NULL,
    [UPD_USER_ID] VARCHAR(30) NULL,
    [SUSPEND] VARCHAR(3) NULL,
    [CHK_BYPASS_YN] VARCHAR(1) NULL,
    [OD_RQ_ID] VARCHAR(5) NULL,
    [BCR_RCV_VAL1] VARCHAR(60) NULL,
    [UPD_DT1] DATETIME NULL,
    [BCR_RCV_VAL2] VARCHAR(60) NULL,
    [UPD_DT2] VARCHAR(26) NULL,
    [BCR_RCV_VAL3] VARCHAR(60) NULL,
    [UPD_DT3] VARCHAR(26) NULL,
    [BCR_RCV_VAL4] VARCHAR(60) NULL,
    [UPD_DT4] VARCHAR(26) NULL,
    [BCR_RCV_VAL5] VARCHAR(60) NULL,
    [UPD_DT5] VARCHAR(26) NULL,
    [BCR_READING] VARCHAR(255) NULL
);
GO

IF OBJECT_ID('dbo.AUTO_SC_WORK','U') IS NOT NULL DROP TABLE dbo.AUTO_SC_WORK;
GO
CREATE TABLE dbo.AUTO_SC_WORK (
    [WH_TYP] VARCHAR(4) NULL,
    [SC_NO] VARCHAR(10) NULL,
    [LUGG_NO] VARCHAR(8) NULL,
    [JOB_TYP] VARCHAR(30) NULL,
    [WRK_TYP] VARCHAR(30) NULL,
    [INS_DT] DATE NULL,
    [JOB_SEQ] VARCHAR(2) NULL,
    [LOG_SEQ] INT NOT NULL,
    [BCR_BOTTOM] VARCHAR(10) NULL,
    [BCR_TOP] VARCHAR(10) NULL,
    [PGR_NM] VARCHAR(20) NULL,
    [LOG_KOR] VARCHAR(100) NULL,
    [TRACK_FROM] VARCHAR(10) NULL,
    [TRACK_TO] VARCHAR(10) NULL,
    [JOB_STA] VARCHAR(10) NULL,
    [RQ_INS_ID] VARCHAR(20) NULL,
    [RQ_INS_DT] DATE NULL,
    [EQP_TYP] VARCHAR(10) NULL,
    [SPARE1] VARCHAR(50) NULL,
    [SPARE2] VARCHAR(50) NULL
);
GO

IF OBJECT_ID('dbo.CV_DEF_INF','U') IS NOT NULL DROP TABLE dbo.CV_DEF_INF;
GO
CREATE TABLE dbo.CV_DEF_INF (
    [WH_TYP] VARCHAR(2) NULL,
    [FR_CV] VARCHAR(10) NULL,
    [TO_CV] VARCHAR(10) NULL,
    [USE_YON] VARCHAR(1) NULL,
    [REMARKS] VARCHAR(200) NULL,
    [WAIT_CV] VARCHAR(10) NULL,
    [BUFFER_CV] VARCHAR(10) NULL
);
GO

IF OBJECT_ID('dbo.SC_HS_DEF','U') IS NOT NULL DROP TABLE dbo.SC_HS_DEF;
GO
CREATE TABLE dbo.SC_HS_DEF (
    [WH_TYP] VARCHAR(4) NULL,
    [SC_NO] VARCHAR(5) NULL,
    [HS_NO] VARCHAR(3) NULL,
    [HS_MC_NO] VARCHAR(5) NULL,
    [DEST_DAT_POS] VARCHAR(2) NULL,
    [DEST_DAT_TOKEN] VARCHAR(5) NULL,
    [DEST_DEF_DAT] VARCHAR(200) NULL,
    [HS_USE_YN] VARCHAR(1) NULL,
    [UPD_DT] DATE NULL,
    [PAIR_HS_NO] VARCHAR(5) NULL,
    [WAIT_TRACK] VARCHAR(5) NULL
);
GO

IF OBJECT_ID('dbo.SC_LEV_DEF','U') IS NOT NULL DROP TABLE dbo.SC_LEV_DEF;
GO
CREATE TABLE dbo.SC_LEV_DEF (
    [WH_TYP] VARCHAR(8) NULL,
    [AGING_TYP] VARCHAR(10) NULL,
    [LEV_CNT] VARCHAR(4) NULL,
    [POS] VARCHAR(4) NULL,
    [SC_NO_LEV1] VARCHAR(10) NULL,
    [SC_NO_LEV2] VARCHAR(10) NULL,
    [SC_NO_LEV3] VARCHAR(10) NULL,
    [SC_NO_LEV4] VARCHAR(10) NULL,
    [TIME] DATETIME NULL
);
GO

IF OBJECT_ID('dbo.DEST_POS_DEF','U') IS NOT NULL DROP TABLE dbo.DEST_POS_DEF;
GO
CREATE TABLE dbo.DEST_POS_DEF (
    [TRACK_NO] VARCHAR(5) NULL,
    [REMARKS] VARCHAR(30) NULL,
    [PRIORITY] INT NULL,
    [GROUP_NO] VARCHAR(5) NULL,
    [WH_TYP] VARCHAR(20) NULL,
    [MC_NO] VARCHAR(5) NULL,
    [RET_CNT] VARCHAR(3) NULL
);
GO

IF OBJECT_ID('dbo.DEAD_LOCK_ZONE_DEF','U') IS NOT NULL DROP TABLE dbo.DEAD_LOCK_ZONE_DEF;
GO
CREATE TABLE dbo.DEAD_LOCK_ZONE_DEF (
    [WH_TYP] VARCHAR(4) NULL,
    [CUR_POS] VARCHAR(10) NULL,
    [BUFFERS] VARCHAR(50) NULL,
    [CUR_DEST_POS] VARCHAR(10) NULL,
    [CHK_DEST_POS] VARCHAR(50) NULL,
    [COUNT] VARCHAR(5) NULL,
    [EQP_STA_CHK_TR] VARCHAR(10) NULL,
    [USE_YN] VARCHAR(1) NULL,
    [REMARK] VARCHAR(100) NULL
);
GO

IF OBJECT_ID('dbo.EQP_MST','U') IS NOT NULL DROP TABLE dbo.EQP_MST;
GO
CREATE TABLE dbo.EQP_MST (
    [WH_TYP] VARCHAR(4) NULL,
    [EQP_TYP] VARCHAR(10) NULL,
    [PLC_NO] VARCHAR(5) NULL,
    [SC_GRP_NO] VARCHAR(3) NULL,
    [PLC_IP] VARCHAR(20) NULL,
    [PLC_PORT_FROM] VARCHAR(5) NULL,
    [PLC_PORT_TO] VARCHAR(5) NULL,
    [SOCK_TIMEOUT] VARCHAR(5) NULL,
    [RETRY_YN] VARCHAR(1) NULL,
    [USE_YN] VARCHAR(1) NULL,
    [CONNECTED_YN] VARCHAR(1) NULL,
    [UPD_DT] DATETIME NULL,
    [REMARKS] VARCHAR(200) NULL,
    [PLC_PORT] VARCHAR(255) NULL,
    [PRIORITY] VARCHAR(3) NULL,
    [BATCH] VARCHAR(255) NULL,
    [PROCESS] VARCHAR(255) NULL
);
GO

IF OBJECT_ID('dbo.WAIT_TRACK','U') IS NOT NULL DROP TABLE dbo.WAIT_TRACK;
GO
CREATE TABLE dbo.WAIT_TRACK (
    [WH_TYP] VARCHAR(3) NULL,
    [DEST_POS] VARCHAR(5) NULL,
    [WAIT_TRACK] VARCHAR(5) NULL,
    [SC_NO] VARCHAR(10) NULL
);
GO

IF OBJECT_ID('dbo.LOOP_CV_USAGE','U') IS NOT NULL DROP TABLE dbo.LOOP_CV_USAGE;
GO
CREATE TABLE dbo.LOOP_CV_USAGE (
    [WH_TYP] VARCHAR(3) NULL,
    [LOOP_NM] VARCHAR(20) NULL,
    [LOOP_CNT] INT NULL,
    [LOOP_USE_CNT] INT NULL,
    [LOOP_USER_USAGE] FLOAT NULL,
    [LOOP_USE_USAGE] FLOAT NULL,
    [UPD_DT_USER_ID] VARCHAR(30) NULL,
    [UPD_DT_DATE] DATE NULL,
    [MES_RQ] VARCHAR(6) NULL
);
GO

IF OBJECT_ID('dbo.EVENT_LOG','U') IS NOT NULL DROP TABLE dbo.EVENT_LOG;
GO
CREATE TABLE dbo.EVENT_LOG (
    [WH_TYP] VARCHAR(4) NULL,
    [ISSUE_DATE] DATE NOT NULL,
    [EVENT_SEQ] VARCHAR(30) NULL,
    [JOB_TYP] VARCHAR(5) NULL,
    [JOB_KIND] VARCHAR(5) NULL,
    [JOB_STATUS] VARCHAR(5) NULL,
    [MC_TYP] VARCHAR(10) NULL,
    [MC_NO] VARCHAR(10) NULL,
    [SOUR_SITE] VARCHAR(10) NULL,
    [DEST_SITE] VARCHAR(10) NULL,
    [LUGG_NO] VARCHAR(10) NULL,
    [CMD_STA] VARCHAR(30) NULL,
    [BCR_BOTTOM] VARCHAR(20) NULL,
    [BCR_TOP] VARCHAR(20) NULL,
    [MC_ERROR_CD] VARCHAR(10) NULL,
    [INS_DT] DATE NULL,
    [INS_USER_ID] VARCHAR(20) NULL,
    [REMARKS] VARCHAR(100) NULL
);
GO

IF OBJECT_ID('dbo.WCS_LOG_PGR','U') IS NOT NULL DROP TABLE dbo.WCS_LOG_PGR;
GO
CREATE TABLE dbo.WCS_LOG_PGR (
    [WH_TYP] VARCHAR(20) NULL,
    [INS_DT] DATETIME NULL,
    [LOG_SEQ] INT NULL,
    [LUGG_NO] VARCHAR(255) NULL,
    [BCR_BOTTOM] VARCHAR(255) NULL,
    [BCR_TOP] VARCHAR(255) NULL,
    [PGR_NM] VARCHAR(255) NULL,
    [LOG_KOR] VARCHAR(255) NULL,
    [TRACK_FROM] VARCHAR(255) NULL,
    [TRACK_TO] VARCHAR(255) NULL,
    [JOB_STA] VARCHAR(255) NULL,
    [RQ_INS_ID] VARCHAR(255) NULL,
    [RQ_INS_DT] DATETIME NULL,
    [EQP_TYP] VARCHAR(255) NULL
);
GO

IF OBJECT_ID('dbo.COMMON_CODE','U') IS NOT NULL DROP TABLE dbo.COMMON_CODE;
GO
CREATE TABLE dbo.COMMON_CODE (
    [CDX_CD] VARCHAR(20) NULL,
    [CCD_CD] VARCHAR(20) NULL,
    [CCD_CD_YN] VARCHAR(1) NULL,
    [CCD_EPR_ORD] INT NULL,
    [CCD_NM_KOR] VARCHAR(200) NULL,
    [CCD_NM_ENG] VARCHAR(200) NULL,
    [CCD_NM_HUN] VARCHAR(200) NULL,
    [CCD_NM_CHIN] VARCHAR(200) NULL,
    [WH_TYP] VARCHAR(11) NULL
);
GO

IF OBJECT_ID('dbo.SEQ_NO_GNR','U') IS NOT NULL DROP TABLE dbo.SEQ_NO_GNR;
GO
CREATE TABLE dbo.SEQ_NO_GNR (
    [WH_TYP] VARCHAR(4) NULL,
    [SEQ_NO_TYP] VARCHAR(10) NULL,
    [SEQ_NO_DATE] VARCHAR(8) NULL,
    [SEQ_NO_BASE] VARCHAR(8) NULL,
    [SEQ_NO_MIN] INT NULL,
    [SEQ_NO_MAX] INT NULL,
    [SEQ_NO_CUR] INT NULL,
    [DATA_LEN] INT NULL,
    [TBL_CHK_YON] VARCHAR(7) NULL,
    [CHK_TBL_ID] VARCHAR(30) NULL,
    [CHK_COL_ID] VARCHAR(30) NULL,
    [REMARKS] VARCHAR(128) NULL,
    [INIT_DATE] VARCHAR(1) NULL,
    [INC_DATE] VARCHAR(1) NULL
);
GO
