<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon />
    <StartupObject>XgtPlcSimulator.Program</StartupObject>
    <AssemblyName>XgtPlcSimulator</AssemblyName>
    <RootNamespace>XgtPlcSimulator</RootNamespace>
  </PropertyGroup>
</Project>
