USE [ECPDB]
GO

ALTER TABLE ZCONFIG_OBSERVABLE_PROTOTYPE  ADD VALUE_INFOMATION VARCHAR(255);
GO 

ALTER TABLE ZCONFIG_OBSERVABLE_PROTOTYPE  ADD REMARK VARCHAR(255);
GO

ALTER TABLE  OBSERVABLE ADD VALUE_INFOMATION VARCHAR(255);
GO 

ALTER TABLE OBSERVABLE ADD REMARK VARCHAR(255);
GO

UPDATE    GUIOBJECT SET ELEMENTID = '' WHERE     (ELEMENTID LIKE 'Label%');
GO

DELETE FROM ZCONFIG_OBSERVABLE_PROTOTYPE;
GO



BULK INSERT  ZCONFIG_OBSERVABLE_PROTOTYPE  FROM 'c:\stocker_temp\observables.ini' WITH 
(
	FIELDTERMINATOR  = '\t',
	ROWTERMINATOR  = '\n'
)
GO


UPDATE    ZCONFIG_OBSERVABLE_PROTOTYPE
SET              VALUE_INFOMATION =
                          (SELECT     VALUE_INFOMATION
                            FROM          ZCONFIG_OBSERVABLE_PROTOTYPE AS PROTO
                            WHERE      (OWNERID = 'RACKMASTER:1') AND (OBSERVABLEID = ZCONFIG_OBSERVABLE_PROTOTYPE.OBSERVABLEID)), REMARK =
                          (SELECT     REMARK
                            FROM          ZCONFIG_OBSERVABLE_PROTOTYPE AS PROTO
                            WHERE      (OWNERID = 'RACKMASTER:1') AND (OBSERVABLEID = ZCONFIG_OBSERVABLE_PROTOTYPE.OBSERVABLEID))
WHERE     (OWNERID LIKE 'RACKMASTER:%') AND (OWNERID <> 'RACKMASTER:1')
GO


UPDATE    ZCONFIG_OBSERVABLE_PROTOTYPE
SET              VALUE_INFOMATION =
                          (SELECT     VALUE_INFOMATION
                            FROM          ZCONFIG_OBSERVABLE_PROTOTYPE AS PROTO
                            WHERE      (OWNERID = 'STOCKERPORT:1') AND (OBSERVABLEID = ZCONFIG_OBSERVABLE_PROTOTYPE.OBSERVABLEID)), REMARK =
                          (SELECT     REMARK
                            FROM          ZCONFIG_OBSERVABLE_PROTOTYPE AS PROTO
                            WHERE      (OWNERID = 'STOCKERPORT:1') AND (OBSERVABLEID = ZCONFIG_OBSERVABLE_PROTOTYPE.OBSERVABLEID))
WHERE     (OWNERID LIKE 'STOCKERPORT:%') AND (OWNERID <> 'STOCKERPORT:1')
GO


UPDATE    ZCONFIG_OBSERVABLE_PROTOTYPE
SET              VALUE_INFOMATION =
                          (SELECT     VALUE_INFOMATION
                            FROM          ZCONFIG_OBSERVABLE_PROTOTYPE AS PROTO
                            WHERE      (OWNERID = 'PROCESSPORT:1') AND (OBSERVABLEID = ZCONFIG_OBSERVABLE_PROTOTYPE.OBSERVABLEID)), REMARK =
                          (SELECT     REMARK
                            FROM          ZCONFIG_OBSERVABLE_PROTOTYPE AS PROTO
                            WHERE      (OWNERID = 'PROCESSPORT:1') AND (OBSERVABLEID = ZCONFIG_OBSERVABLE_PROTOTYPE.OBSERVABLEID))
WHERE     (OWNERID LIKE 'PROCESSPORT:%') AND (OWNERID <> 'PROCESSPORT:1')
GO

UPDATE    ZCONFIG_OBSERVABLE_PROTOTYPE
SET              VALUE_INFOMATION =
                          (SELECT     VALUE_INFOMATION
                            FROM          ZCONFIG_OBSERVABLE_PROTOTYPE AS PROTO
                            WHERE      (OWNERID = 'FFU:1') AND (OBSERVABLEID = ZCONFIG_OBSERVABLE_PROTOTYPE.OBSERVABLEID)), REMARK =
                          (SELECT     REMARK
                            FROM          ZCONFIG_OBSERVABLE_PROTOTYPE AS PROTO
                            WHERE      (OWNERID = 'FFU:1') AND (OBSERVABLEID = ZCONFIG_OBSERVABLE_PROTOTYPE.OBSERVABLEID))
WHERE     (OWNERID LIKE 'FFU:%') AND (OWNERID <> 'FFU:1')



GO
UPDATE    ZCONFIG_OBSERVABLE_PROTOTYPE
SET              VALUE_INFOMATION =
                          (SELECT     VALUE_INFOMATION
                            FROM          ZCONFIG_OBSERVABLE_PROTOTYPE AS PROTO
                            WHERE      (OWNERID = '10101') AND (OBSERVABLEID = ZCONFIG_OBSERVABLE_PROTOTYPE.OBSERVABLEID)), REMARK =
                          (SELECT     REMARK
                            FROM          ZCONFIG_OBSERVABLE_PROTOTYPE AS PROTO
                            WHERE      (OWNERID = '10101') AND (OBSERVABLEID = ZCONFIG_OBSERVABLE_PROTOTYPE.OBSERVABLEID))
WHERE  (OWNERID LIKE '[1-9]____') AND (OWNERID <> '10101')
GO



UPDATE ZCONFIG_OBSERVABLE_PROTOTYPE SET VALUE_INFOMATION='' where VALUE_INFOMATION IS NULL;
GO

UPDATE ZCONFIG_OBSERVABLE_PROTOTYPE SET REMARK='' where REMARK IS NULL;
GO


delete from observable where OBSERVABLEID LIKE '%LIFT%' or  OBSERVABLEID LIKE '%LFT%' ;
GO


INSERT INTO 
	Observable
		(	OWNERID, OWNERTYPE, OBSERVABLEID, OBSERVABLEGUID, OBSERVABLEPATH, ACCESSTYPE, 
			DATATYPE, MIN, MAX, DRIVERNO, MONFLAG, CONNECTSTRING, DESCRIPTION, LOG_ENABLE) 
		SELECT     
			OWNERID, OWNERTYPE, OBSERVABLEID, OBSERVABLEGUID, OBSERVABLEPATH, ACCESSTYPE, 
			DATATYPE, MIN, MAX, DRIVERNO, MONFLAG, CONNECTSTRING, DESCRIPTION, LOG_ENABLE
			FROM         ZCONFIG_OBSERVABLE_PROTOTYPE      
			WHERE     (OBSERVABLEID LIKE '%LIFT%' or  OBSERVABLEID LIKE '%LFT%') AND 
								(OWNERID IN  (SELECT ID FROM RACKMASTER));
GO                            
                            
UPDATE    OBSERVABLE
SET              
MONFLAG =
						(SELECT     MONFLAG
						FROM          ZCONFIG_OBSERVABLE_PROTOTYPE
						WHERE      (OBSERVABLEID = OBSERVABLE.OBSERVABLEID) AND (OWNERID = OBSERVABLE.OWNERID))
, 
DESCRIPTION =
							(SELECT     DESCRIPTION
							FROM          ZCONFIG_OBSERVABLE_PROTOTYPE AS ZCONFIG_OBSERVABLE_PROTOTYPE_2
							WHERE      (OBSERVABLEID = OBSERVABLE.OBSERVABLEID) AND (OWNERID = OBSERVABLE.OWNERID))
,
LOG_ENABLE =
							(SELECT     LOG_ENABLE
							FROM          ZCONFIG_OBSERVABLE_PROTOTYPE AS ZCONFIG_OBSERVABLE_PROTOTYPE_1
							WHERE      (OBSERVABLEID = OBSERVABLE.OBSERVABLEID) AND (OWNERID = OBSERVABLE.OWNERID))
,
VALUE_INFOMATION =
							(SELECT     VALUE_INFOMATION
							FROM          ZCONFIG_OBSERVABLE_PROTOTYPE AS ZCONFIG_OBSERVABLE_PROTOTYPE_1
							WHERE      (OBSERVABLEID = OBSERVABLE.OBSERVABLEID) AND (OWNERID = OBSERVABLE.OWNERID))
,
REMARK =
							(SELECT     REMARK
							FROM          ZCONFIG_OBSERVABLE_PROTOTYPE AS ZCONFIG_OBSERVABLE_PROTOTYPE_1
							WHERE      (OBSERVABLEID = OBSERVABLE.OBSERVABLEID) AND (OWNERID = OBSERVABLE.OWNERID));
							
GO