#if !defined(AFX_EXCOM_H__8F98CB2C_ECCB_43F6_B73D_A8C2C9424A5E__INCLUDED_)
#define AFX_EXCOM_H__8F98CB2C_ECCB_43F6_B73D_A8C2C9424A5E__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CeXCom wrapper class

class AFX_EXT_CLASS CeXCom : public CWnd
{
protected:
	DECLARE_DYNCREATE(CeXCom)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x717b131f, 0xe3dd, 0x4053, { 0x87, 0xa6, 0xc4, 0xe2, 0xb2, 0xe9, 0x83, 0xc2 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	short GetDeviceID();
	void SetDeviceID(short);
	short GetStream();
	void SetStream(short);
	short GetFunction();
	void SetFunction(short);
	long GetSystemBytes();
	void SetSystemBytes(long);
	short GetWbit();
	void SetWbit(short);
	short GetRbit();
	void SetRbit(short);
	short GetEbit();
	void SetEbit(short);
	short GetPType();
	void SetPType(short);
	short GetSType();
	void SetSType(short);
	short GetBlock();
	void SetBlock(short);
	long GetHeaderSize();
	void SetHeaderSize(long);
	long GetMsgSize();
	void SetMsgSize(long);

// Operations		
public:
	short Initialize(LPCTSTR sCfgFile);
	short Close();
	short Start();
	short Stop();
//	short MakeSecsMsg(long* plMsgId, short nDevId, short nStrm, short nFunc, long lSysByte);
	long MakeSecsMsg(long* plMsgId, short nDevId, short nStrm, short nFunc, long lSysByte);


	short Send(long lMsgId);
	short LoadSecsMsg(long* plMsgId, short* pnDevId, short* pnStrm, short* pnFunc, long* plSysByte, short* pnWbit);
	void CloseSecsMsg(long lMsgId);
	short GetListItem(long lMsgId, short* pnItems);
	short GetBinaryItem(long lMsgId, short* pnValue, long* plCount, long lSize);
	short GetBoolItem(long lMsgId, short* pnValue, long* plCount, long lSize);
	short GetAsciiItem(long lMsgId, BSTR* psValue, long* plCount);
	short GetJis8Item(long lMsgId, BSTR* psValue, long* plCount);
	short GetI1Item(long lMsgId, short* pnValue, long* plCount, long lSize);
	short GetI2Item(long lMsgId, short* pnValue, long* plCount, long lSize);
	short GetI4Item(long lMsgId, long* plValue, long* plCount, long lSize);
	short GetI8Item(long lMsgId, long* plValue, long* plCount, long lSize);
	short GetU1Item(long lMsgId, short* pnValue, long* plCount, long lSize);
	short GetU2Item(long lMsgId, long* plValue, long* plCount, long lSize);
	short GetU4Item(long lMsgId, double* prValue, long* plCount, long lSize);
	short GetU8Item(long lMsgId, double* prValue, long* plCount, long lSize);
	short GetF4Item(long lMsgId, float* prValue, long* plCount, long lSize);
	short GetF8Item(long lMsgId, double* prValue, long* plCount, long lSize);
	short SetListItem(long lMsgId, short nItems);
	short SetBinaryItem(long lMsgId, short* pnValue, long lCount);
	short SetBoolItem(long lMsgId, short* pnValue, long lCount);
	short SetAsciiItem(long lMsgId, LPCTSTR pszValue, long lCount);
	short SetJis8Item(long lMsgId, LPCTSTR pszValue, long lCount);
	short SetI1Item(long lMsgId, short* pnValue, long lCount);
	short SetI2Item(long lMsgId, short* pnValue, long lCount);
	short SetI4Item(long lMsgId, long* plValue, long lCount);
	short SetI8Item(long lMsgId, long* plValue, long lCount);
	short SetU1Item(long lMsgId, short* pnValue, long lCount);
	short SetU2Item(long lMsgId, long* plValue, long lCount);
	short SetU4Item(long lMsgId, double* prValue, long lCount);
	short SetU8Item(long lMsgId, double* prValue, long lCount);
	short SetF4Item(long lMsgId, float* prValue, long lCount);
	short SetF8Item(long lMsgId, double* prValue, long lCount);
	short EnableLog(short nLogType, short nEnabled);
	short GetHeaderBytes(long lMsgId, short* pnHeader, short nSize);
	long GetMsgBytes(long lMsgId, short* pnMsg, long lSize);
	short SetHeaderBytes(long lMsgId, short* pnHeader, short nSize);
	long SetMsgBytes(long lMsgId, short* pnMsg, long lSize);
	short GetAlarmMsgInfo(long lMsgId, short* pnDevId, short* pnStrm, short* pnFunc, long* plSysByte, short* pnWbit);
	short DebugInfo(short* pnInfo);
	long GetSysBytes(long lMsgId);
	short SetStringItem(long lMsgId, BSTR* pbstrValue, long lCount);
	short SetWBit(long lMsgId, short nWBit);
	short GetInvalidMsgInfo(long lMsgId, short* pnDevId, short* pnStrm, short* pnFunc, long* plSysByte, short* pnWbit);
	short MakeSpoolStream(long lMsgId);
	short ProcExternalStream(short* pnMsg, long lSize);
	CString GetParam(LPCTSTR pszParamName);
	short SetParam(LPCTSTR psParamName, LPCTSTR psVal);
	CString GetStringItem(long lMsgId, long* plCount);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_EXCOM_H__8F98CB2C_ECCB_43F6_B73D_A8C2C9424A5E__INCLUDED_)
